Infomaniak/ios-kDrive

- kDrive/Resources/Assets.xcassets/Colors/buttonDisabledBackgroundColor.colorset/Contents.json
- kDrive/Resources/Assets.xcassets/Colors/buttonDisabledTitleColor.colorset/Contents.json
- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
- kDriveCore/Utils/IKLargeButton.swift
- PhotoSyncSettingsViewController: cache le bouton save tant que le user n'a pas fait de changement.
- fix le bug IKLargeButton ne change pas de couleur quand on passe de light à dark mode.
> Save button

- kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
- kDrive/UI/View/Files/Upload/UploadTableViewCell.swift
- kDriveCore/Data/UploadQueue/UploadQueue.swift
- Upload queue view controller improvements:
- Prevent creating a new Realm each time in upload queue view controller
- Sort files
- Check network status for resuming or suspending upload queue
> Upload queue improvements: Realm creation, sorting, and network

- kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
Hide "see folder" action if no parent's file is available
> [T989] Hide "see folder" action if not available

- kDrive/UI/Controller/MainTabViewController.swift
- kDrive/UI/Controller/Menu/Trash/TrashCollectionViewController.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/Cache/DriveInfosManager.swift
- kDriveCore/Data/DownloadQueue/DownloadOperation.swift
- kDriveCore/Data/Models/File.swift
- kDriveFileProvider/FileProviderExtension+Actions.swift
- kDriveFileProvider/FileProviderExtension.swift
- kDriveFileProvider/FileProviderItem.swift
> Fix freeze file activities

- kDriveCore/Data/Cache/AccountManager.swift
- kDriveCore/Data/UploadQueue/PhotoLibraryUploader.swift
- kDriveCore/Data/UploadQueue/UploadOperation.swift
Use an optional value for `settings` in `PhotoLibraryUploader` to prevent crashes
> Photo sync settings optional

- kDrive/AppDelegate.swift
- kDriveCore/Data/Models/File.swift
- kDriveCore/Data/Models/UploadFile.swift
- kDriveCore/Utils/URL+Extension.swift
- kDriveFileProvider/FileProviderItem.swift
Using the `UTI` struct could result in an incorrect type identifier for the File Provider Item. Fixes #81.
> Fix disabled files in File Provider

- kDriveCore/Data/UploadQueue/BackgroundUploadSessionManager.swift
- kDriveCore/Data/UploadQueue/UploadOperation.swift
- kDriveCore/Data/UploadQueue/UploadQueue.swift
This PR removes the `cleanupOrphanFiles` method which was flawed and correctly handles `shouldRemoveAfterUpload` attribute.
It also handles missing errors during upload.
> Correctly remove file after upload

- kDrive/UI/Controller/Files/FileListViewController.swift
The collection view was reloading for every page fetched
> Prevent  blinking each fetch next page

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/MainTabViewController.swift
- kDrive/UI/View/Files/Upload/UploadTableViewCell.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/DownloadQueue/BackgroundDownloadSessionManager.swift
- kDriveCore/Data/Models/UploadFile.swift
- kDriveCore/Data/UploadQueue/BackgroundUploadSessionManager.swift
- kDriveCore/Data/UploadQueue/UploadOperation.swift
- kDriveCore/Data/UploadQueue/UploadQueue.swift
- kDriveCore/Utils/Logging.swift
The upload queue had to be modified a lot resolve multiple issues we had regarding background upload with extensions.
Each extension now has its own background session identifier. While working on those improvements I noticed some issues with our current handling of background session when rescheduling an upload that I also fixed.
As this is a large rewrite of the current upload implementation we still have a lot of stability testing to do:
> Fix share extension

- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Menu/Trash/TrashViewController.swift
- kDrive/Utils/UIConstants.swift
- kDriveCore/Utils/IKSnackBar.swift
Use a different `UIWindow` to present snackbars. It simplifies the workflow and prevents snackbars to be hidden when navigating the app.
> Improve snackbar with UIWindow

- kDriveCore/Data/Cache/AccountManager.swift
In some cases errors were sent before Sentry User Id was set.
> Correctly set sentry user id

- kDriveCore/Data/UploadQueue/PhotoLibraryUploader.swift
There was an issue with predicate when disabling either pictures or screenshot in photo sync
> Fix photo sync predicates

- kDriveCore/Data/Cache/DriveFileManager.swift
We noticed that favorite activities are received even for other users. Therefore, our method was incorrect. Simply updating the file in Realm seems to work.
> Fix favorite activity

- .package.resolved
- kDrive/UI/Controller/Files/ColorSelectionFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/Search/DateRangePickerViewController.swift
- kDriveCore/Data/Api/ApiRoutes.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Api/Endpoint.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/Models/DriveError.swift
- kDriveCore/Data/Models/File.swift
- kDriveCore/Data/Models/UploadFile.swift
- kDriveTests/DriveApiTests.swift
Preparing foundations for API v2:
- New `Endpoint` struct to improve API endpoints management
- Update dependencies (Alamofire 5.5 includes support for Swift Concurrency)
- New request helper methods in API fetcher to use `Endpoint` and async/await
- Rewrite folder color API methods using this new mechanism
> Prepare for API v2

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
Refactoring navigation title setting because it could lead to a crash when previewFiles is not initialized
> Fix preview title

- kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
- kDrive/UI/View/Files/Upload/UploadTableViewCell.swift
- kDriveCore/Data/UploadQueue/UploadQueue.swift
Closes #603 
Fixes :
- bad icons displayed on UploadTableViewCell
- cancel button that doesn't work after an error
- wrong size of file icons
- 0% progression when restarting a download
> Upload table view cell wrong icons

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
To reproduce bug on release 4.2.0 :
- select a cell
- click on 'select all'
- scroll
> Cells not selected with "select all"

- kDrive/UI/Controller/Files/File List/MultipleSelectionFileListViewModel.swift
- kDrive/UI/Controller/Files/Save File/SelectFolderViewController.swift
Moving files is allowed to any destination directories from fake roots but only move the necessary files.
Close #581
> Fix disabled directories move multiple selection

- .swiftlint.yml
Increase argument count limit for swiftlint to stay consistant with sonarcloud
> Increase argument count limit swiftlint

- kDrive/UI/Controller/Create File/PlusButtonFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
- kDrive/Utils/FileActionsHelper.swift
- kDrive/Utils/MatomoUtils.swift
- Rename `SelectFloatingPanelTableViewController` to `MultipleSelectionFloatingPanelViewController`
- Refactor file actions used in both `MultipleSelectionFloatingPanelViewController` and `FileActionsFloatingPanelViewController` in `FileActionsHelper`
> Refactor SelectFloatingPanelTableViewController

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/View/Files/FileCollectionViewCell.swift
Fixes #714 
In iOS 15, prefetching seems to mess things up. This fixes it.
> Fix file cell selection mode

- kDrive/AppDelegate.swift
- kDriveCore/Data/Models/File.swift
- Fix: In some cases users could have a badge of pending upload count (from the old nextcloud app)
- Fix: If a file is removed from realm before thumbnail fetch, realm crashes
> Small fixes

- kDrive/UI/Controller/Files/RecentActivityFilesViewController.swift
Prevent crash when opening RecentActivityFilesViewController multiple times.
> Detach objects before adding to view

- kDriveCore/Data/Cache/BackgroundRealm.swift
- kDriveCore/Data/UploadQueue/PhotoLibraryUploader.swift
Realm would crash the app because of an invalid object being accessed for the following reasons:
- Disable photosync while enumerating photos to sync
- Write upload buffer parent with deleted parent
> Fix invalid realm

- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Utils/Logging.swift
In some cases migration wasn't working when migrating embedded objects.
Rights are removed as they will be recreated when dowloading files again.
> Fix migration

- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
When we are downloading an archive in multiple selection if we tap again to cancel the download but don't click cancel, the cell was resetted and lost the download progress.
> Prevent resetting cell status archive download

- kDrive/UI/View/Files/FileDetail/ShareLink/UsersAccessTableViewCell.swift
- kDriveCore/Data/Models/DriveUser.swift
- kDriveCore/Data/Models/FileAccess.swift
Object `drive_user` has been updated. Property `role` can have values `admin`/`user`/`external`, and property `type` (`shared`/`main`) is deprecated.
_(Preprod-next)_
> Object "drive_user": updated with "role"

- .package.resolved
- Project.swift
ios-core 1.16 fixes concurrent access on ReachabilityListener which could help with issues related to KDRIVE-IOS-2N8.
> Use ios-core 1.16

- kDriveCore/Data/UploadQueue/PhotoLibraryUploader.swift
Use autoreleasepool to discard data as soon as possible as we are in a background queue.
> Potential fix for KDRIVE-IOS-2XH

- kDrive/AppDelegate.swift
Fix for Sentry: KDRIVE-IOS-2PF
> Cancel observation after first call

- kDrive/AppDelegate.swift
- kDriveCore/Data/UploadQueue/UploadOperation.swift
Fixes #910 
- When we upload a file which is available offline, we should keep this info
- When we upload a file edited locally, the `lastModifiedAt` provided by the back-end is slightly greater than the `modificationDate` attribute of the local file
> Fix offline sync

- kDrive/UI/Controller/Files/Categories/ManageCategoriesViewController.swift
- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
- kDrive/Utils/FileActionsHelper.swift
To follow the same logic as android: [android#937](https://github.com/Infomaniak/android-kDrive/pull/937)
> Manage categories: only use API call with several files

- kDriveCore/Data/UploadQueue/Operation/UploadOperation.swift
fix: Using `relativePath`, if any, to create sub folders for Asset upload.
chore: Refactored getUploadSessionOrCreate to be easier to understand.
> Using relativePath, if any, to create sub folders for Assets

- kDriveCore/Data/UploadQueue/Servicies/PhotoLibraryUploader.swift
Prevent from reuploading the same picture on automatic syncronisation.
Mimmic the Android way of doing it. Based on generated name (not URI) as it is built differently.
Optimized Realm request.
> Prevent re-uploading the same picture on automatic sync

- kDriveCore/Data/UploadQueue/Operation/UploadOperation+Error.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperationable.swift
- kDriveCore/Data/UploadQueue/Queue/UploadQueue+Queue.swift
- A loop may occur when a session is not valid, we try to delete it from the remote, which fails, so we try to remove it …
- Also refactored a bit to differenciate more in the error handling.
> Prevent loop in cancel session

- kDrive/UI/Controller/Files/FileDetailViewController.swift
In some cases, the view had already disappeared when coming back from state restoration and waiting for async code, the tableview reload caused a crash.
> fix: Do not update tableview if it already disappeared

- .package.resolved
- Project.swift
- kDriveCore/Data/Models/DriveError.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+Error.swift
- kDriveCore/Data/UploadQueue/Servicies/PhotoLibraryUploader+Scan.swift
- kDriveCore/Utils/ExpiringActivity.swift
- kDriveCore/Utils/NotificationsHelper.swift
- kDriveCore/Utils/PHAsset+Exension.swift
- kDriveCore/Utils/PHAsset/PHAsset+Exension.swift
- kDriveCore/Utils/PHAsset/PHAssetNameProvider.swift
- kDriveTests/kDriveCore/Files/UTPHAssetNameProvider.swift
- Added more logging for errors presented to the user
- Rollback to the original upload naming scheme
- Unit test upload naming scheme
- Use TolerantDispatchGroup to harden ExpiringActivity
> Revert file naming convention

- kDriveCore/Data/MQService/MQService.swift
MQTT throws a fatal error in case we deinit without shutting down
> fix: Correctly shutdown MQTT client on deinit

- kDrive/AppDelegate.swift
- kDriveCore/Data/DownloadQueue/DownloadQueue.swift
- kDriveCore/Data/UploadQueue/Queue/UploadQueue+Queue.swift
- kDriveCore/Data/UploadQueue/Servicies/PhotoLibraryUploader+Scan.swift
- kDriveCore/Utils/Constants.swift
- kDriveCore/Utils/KeychainHelper.swift
- kDriveCore/Utils/Sentry/SentryDebug+Realm.swift
- kDriveCore/Utils/Sentry/SentryDebug+Upload.swift
- kDriveCore/Utils/Sentry/SentryDebug.swift
If stopping the upload queue takes too much time when trying to force close the app.
We gracefully exit before the system kills the app. 
Which currently shows a crash message to end users on TestFlight and counting as a crash in statistics.
> fix: Prevent a crash message on TestFlight when force closing the app.

- Project.swift
- Tuist/ProjectDescriptionHelpers/Constants.swift
- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
- kDrive/Utils/MatomoUtils.swift
- kDriveCore/Utils/Logging.swift
- kDriveTestShared/TestsPreconditions.swift
In order to control the behaviour of the app in Test mode, a new TEST flag was introduced. (like in Mail)
It is used to disable Atlantis in Test mode between other things.
A test was also added to make sure the Flag is correctly set.
> feat: Explicit atlantis disabled in tests

- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/Models/Upload/UploadingSessionTask.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+PHAsset.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+UploadChunk.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+UploadSession.swift
Currently a new file corresponding to the PHAsset is fetched every time an upload session is restarted.
Because of how we get the PHAsset the new file has a new file and is effectively duplicated with a new name. Old files are never cleared because we only clear the new file upon upload completion.
> fix: Prevent refetching PHAsset

- .github/CODEOWNERS
This pull request removes the CODEOWNERS file, allowing us to select our own reviewers or fallback to the iOS team if no specific reviewer is necessary. This change is expected to improve our GitHub notifications.
> feat: Remove CODEOWNERS file

- kDriveCore/Data/UploadQueue/Queue/UploadParallelismHeuristic.swift
- kDriveCore/Data/UploadQueue/Queue/UploadQueue.swift
In low power mode, we want to reduce the upload parallelism.
Also
In extreme scenarios, uploading can overheat the device. In such case, we reduce parallelism.
> feat: Reduce Upload parallelism in critical thermal state or low power mode

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController+FooterButtonDelegate.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
- kDrive/Utils/AppFactoryService.swift
- kDriveActionExtension/ActionNavigationController.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/DownloadQueue/DownloadArchiveOperation.swift
- kDriveCore/Data/DownloadQueue/DownloadOperation.swift
- kDriveCore/Data/DownloadQueue/DownloadQueue.swift
- kDriveCore/Data/UploadQueue/Chunk/RangeProviderGuts.swift
- kDriveCore/Data/UploadQueue/Queue/UploadParallelismHeuristic.swift
- kDriveCore/Data/UploadQueue/Queue/UploadQueue+Queue.swift
- kDriveCore/Data/UploadQueue/Queue/UploadQueue.swift
- kDriveCore/Services/AppContextService.swift
- kDriveCore/Utils/Files/FileImportHelper.swift
- kDriveCore/Utils/Logging.swift
- kDriveCore/Utils/NotificationsHelper.swift
- kDriveFileProvider/FileProviderExtension.swift
- kDriveShareExtension/ShareNavigationViewController.swift
Under some circumstances, it seems the upload starts from the share extension and breaks the current expectation of only the main app runs the uploads.
> fix: ShareExtension fails to upload

- kDriveCore/DI/FactoryService.swift
- kDriveCore/Data/Cache/DriveInfosManager.swift
- kDriveCore/Data/Cache/DriveInfosManager/DriveInfosManager+FileProvider.swift
- kDriveCore/Data/Cache/DriveInfosManager/DriveInfosManager.swift
- kDriveCore/Data/UploadQueue/Queue/UploadQueue+Notifications.swift
- kDriveCore/Utils/AbstractLog+Category.swift
- kDriveCore/Utils/FileProvider/FileProviderDomain+Identifier.swift
- kDriveCore/Utils/Sentry/SentryDebug.swift
- kDriveTests/kDrive/Launch/ITAppLaunchTest.swift
- kDriveTests/kDrive/Launch/UTRootViewControllerState.swift
Some fixes related to the `Files.app` behaviour:
- fix: Make sure no Paused Notification is produced by the FileProvider.
- fix: Removed a race condition while registering a FileProviderDomain.
- fix: Explicitly signal FileProvider when it is updated.
Also improved the situation regarding: 
- chore: Sentry tracking with a dedicated Log.driveInfosManager() channel.
- refactor: Split the _DriveInfosManager's FileProvider_ related code.
> fix: FileProvider

- kDrive/UI/Controller/MainTabViewController.swift
- kDrive/UI/View/Menu/MainTabBar.swift
Fix the dark screen when you tap a bit under the (+) button as there is a TabBar button that links to no ViewController.
> fix: Dark screen when tap under the middle TabBarButton

- kDriveCore/Data/Cache/AccountManager.swift
- kDriveTests/kDrive/Launch/ITAppLaunchTest.swift
- kDriveTests/kDrive/Launch/MockAccountManager.swift
- kDriveTests/kDrive/Launch/UTRootViewControllerState.swift
First PR for AccountManager improvements. The refactor of AccountManager will be splitted in multiple PRs for improved readability.
This first PRs simply uses the same thread safe types as Mail to access critical properties.
> feat: Safer AccountManager

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
- kDriveCore/Utils/Sentry/SentryDebug+Upload.swift
When the relatively complex layers of inheritance of `FileListViewController` are calling the public setter of `viewModel.files`, this update is not covered by observation and does not propagate back to the viewController. 
Therefore, an extra update call should be generated to be consistent.
This would also match the observation I made that this bug tends to show up near the init of the view controller, and crash quickly when it appears. This can also be seen in the Sentry breadcrumbs.
I generate an extra update when and only when the public setter is called. 
This has no change on the existing realm observation of uploading content for instance, and does not change the animations (I tested a bit, looks fine)
The first init of the view controller generates an extra update that I hope …
> fix: Experimental fix for crash in FileListViewController

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/Menu/StorageTableViewController.swift
- kDriveCore/Data/UploadQueue/Servicies/FreeSpace/CleanSpaceActions.swift
- kDriveCore/Data/UploadQueue/Servicies/FreeSpace/FreeSpaceService.swift
When space runs low, we clear the temporary files, that can be safely removed, while keeping user data safe.
> feat: Clear temp files on exit if device is low on space

- Tuist/ProjectDescriptionHelpers/ExtensionTarget.swift
Missing XIB in share extension make it crash when used.
> fix: Share extension crash when selecting upload photo in HEIC mode

- kDriveCore/Data/DownloadQueue/DownloadQueue.swift
- kDriveCore/Data/Models/Upload/UploadFile.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation.swift
- kDriveCore/Data/UploadQueue/Queue/UploadQueue+Queue.swift
- kDriveCore/Data/UploadQueue/Queue/UploadQueueable.swift
- kDriveFileProvider/FileProviderExtension.swift
A copy of a file was kept when an upload was cancelled. This is no longer the case.
> fix: Fix import folder taking a lot of space

- kDrive/AppDelegate.swift
- kDriveCore/DI/FactoryService.swift
- kDriveCore/Data/Models/Upload/UploadFile.swift
- kDriveCore/Data/UploadQueue/Queue/UploadQueue.swift
- kDriveCore/Data/UploadQueue/Servicies/FreeSpace/FreeSpaceService.swift
Making sure files in the import folder are used by an upload in progress tracked in DB, else the file is orphan and meets the void.
Note: The upload queue must be stopped to perform this work, therefore processing it when closing the app is preferable for now.
Superseeding https://github.com/Infomaniak/ios-kDrive/pull/1176
> fix: Clean ophan files master

- kDriveCore/Data/Cache/AccountManager.swift
- kDriveCore/Data/DownloadQueue/DownloadQueue.swift
FileProvider was broken by dead code. Now calling directly the correct `getDrive` method.
> fix: Correct get drive method.

- kDriveCore/Data/Api/Endpoint.swift
Upload restart / Session negotiation was broken on APIV3 branch.
Looks like the getSession call was to be kept in V2, V3 does not exist
> fix: Upload Session retry sends 404

- kDrive/Resources/de.lproj/Localizable.strings
- kDrive/Resources/en.lproj/Localizable.strings
- kDrive/Resources/es.lproj/Localizable.strings
- kDrive/Resources/fr.lproj/Localizable.strings
- kDrive/Resources/it.lproj/Localizable.strings
- kDriveCore/Data/Models/DriveError.swift
A folder cannot contain more than 100'000 files. If we try to upload a file in such a folder, the operation will fail.
We now display a more explicit message when the `limit_exceeded_error` occurs.
> feat(DriveError): Handle `limit_exceeded_error`

- kDriveCore/Data/Cache/DriveFileManager.swift
File entity property name changed, this PR only fixes that.
Before an invalid name in the predicate was crashing the app when filtering by file type offline.
> fix: Search offline works when filtering by file type.

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/LockedAppViewController.swift
- kDriveActionExtension/ActionNavigationController.swift
- kDriveFileProvider/FileProviderExtension.swift
- kDriveShareExtension/ShareNavigationViewController.swift
Making sure the userId is set early in sentry to track crashes in a useful way. It is now set before Realm has a chance of migrating.
Following the work done in a [sister PR](https://github.com/Infomaniak/ios-kMail/pull/1440#pullrequestreview-2085580655) on the Mail side
Did non regression tests on app and extension. Did not notice anything.
> fix: Make sure to set the UserID early for sentry error tracking

- kDrive/UI/Controller/Home/HomeRecentFilesController.swift
- kDrive/UI/Controller/Home/HomeViewController.swift
- kDrive/UI/Controller/Menu/Trash/TrashListViewModel.swift
- kDrive/UI/View/Home/HomeLastPicCollectionViewCell.swift
- kDriveCore/Data/Models/DriveUser.swift
https://github.com/Infomaniak/ios-kDrive/assets/121806582/04d9bd34-05e2-4c3e-a258-087db7441368
> fix: Update gallery after a file suppression

- kDriveCore/Utils/ExpiringActivity.swift
- kDriveCore/Utils/PHAsset/PHAssetIdentifier.swift
Sometimes the upload queue is stuck when calling `bestResourceSHA256` or `baseImageSHA256` this happens if pictures are stored on iCloud. 
From what I've observed it is because `PHAssetResourceManager.default().requestData` or `asset.requestContentEditingInput` returns directly instead of switching threads. We end up calling group.leave before group.enter and so we end up waiting indefinitely on group.wait. 
This would result in a soft lock blocking all cooperative thread pools.
> fix: Ensure we enter before trying to retrieve the resource

- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
- kDriveCore/Utils/Files/FileImportHelper.swift
The app was keeping a copy of files outside the import folder in specific conditions.
The app no longer does that, and uses the import folder.
A further PR will make sure on cleanup to remove said files if no longer in use.
> fix: FileImportHelper use the dedicated import folder, not group app folder

- kDrive/UI/Controller/Menu/StorageTableViewController.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/Cache/DriveInfosManager/DriveInfosManager.swift
- kDriveCore/Data/Models/File.swift
- kDriveCore/Data/UploadQueue/Servicies/FreeSpace/FreeSpaceService.swift
- kDriveCore/Utils/Logging.swift
- kDriveCore/Utils/Sentry/SentryDebug+Misc.swift
- kDriveCore/Utils/Sentry/SentryDebug.swift
Last beta shown that some files were still missing from `StorageTableViewController`
This PR aims at displaying a more correct total app space usage and to cleanup legacy import files.
- Calculation of the total Space used is more complete
- Counting Entire App Group directory, App Library and App Documents directory.
- Sentry event to keep a dashboard of space usage.
- Clean legacy import folders automatically on existing clean-up process.
> fix: Storage space report improvements

- kDrive/UI/Controller/Home/SelectSwitchDriveDelegate.swift
- kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
Root is loaded for the current drive and the current account on update but not once we switch drive. 
Also the root was loaded twice in `initRoot` by 2 different calls.
This PR ensures we load in the background the root while we switch.
It also removes the second call.
> fix: Correctly load root on switch

- kDrive/SceneDelegate.swift
- kDrive/Utils/FileActionsHelper.swift
- kDriveCore/Data/Cache/PdfPreviewCache.swift
- kDriveCore/Data/Models/File.swift
Now that we have access to `revisedAt` which gives a date for the modification of the file we can use it to compare with the local file date.
> fix: Use revisedAt instead of lastModifiedAt where possible

- kDriveCore/Data/Api/FileWith.swift
This reenables thumbnails in home activities
> fix: Add missing fileSupportedBy for activities

- kDrive/AppRestorationService.swift
- kDriveActionExtension/Info.plist
- kDriveFileProvider/Info.plist
- kDriveShareExtension/Info.plist
Share extension is crashing since the SceneDelegate migration. This fixes that.
> fix: Extension main activity missing

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController+Actions.swift
- kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkTableViewCell.swift
- kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkTableViewCell.xib
- kDriveCore/Data/Models/File+URL.swift
- kDriveCore/Data/Models/ShareLink.swift
Any file has a private sharing URL that can be constructed, this takes care of that and brings the iOS app on par with the web.
> feat: Private share link can be shared like on the web

- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDriveAPITests/kDriveCore/DriveApiTests.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Api/Endpoint.swift
- kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
Read commit by commit:
- (417cc90fabb154f77d13f951ed00a9a89d76d902) Trash -> restore / delete permanently use V2
- (12387860dc3153893c21d3d95fdb98a4024f603a) Activities for file details -> use cursor
- (5391da64ea1b9e13bcd68d00e0a6447f7437a681) Remove dead code
- (f6df90dfabfca9a40956c36a068b180da95a2964) Remove default argument for searchFiles
> fix: Use correct endpoints

- kDriveCore/Services/AppContextService.swift
- kDriveTests/kDriveCore/UTAppContextServiceable.swift
Upload does not start right away when uploading a picture, this is the root cause.
Added some super simple tests to make sure of it.
> fix: Correct AppContextService.isExtension logic

- kDriveCore/Data/Models/File.swift
Realm can't sort files correctly: [issue](https://github.com/realm/realm-swift/issues/2970).
Keep sortedName as lowercased to sort files alphabetically (and case insensitive).
> fix: Keep sortedName as lowercased

- kDrive/AppRouter.swift
The "locate" button in the snackbar after an upload wasn't correctly redirecting to the `FileListViewController` if the user wasn't already in a `FileListViewController` (eg. in the `RootMenuViewController`)
> fix(AppRouter): Correctly navigate to file list when in root menu

- kDrive/UI/Controller/Files/RootMenuViewController.swift
This prevents showing the "Shared" folder in the root. This also restrict to only showing the folders we want.
> fix: Ensure we only show team and private folders in root

- kDrive/UI/Controller/Menu/MenuViewController.swift
- kDrive/UI/View/Menu/MenuTopTableViewCell.swift
- kDrive/UI/View/Menu/MenuTopTableViewCell.xib
**Before**
Tap only available on the button
**After**
Click anywhere on the stackView (icon, label and button)
> fix: Extend switch drive tappable area

- kDrive/UI/Controller/Files/ColorSelectionFloatingPanelViewController.swift
Something changed in the sizing mecanism of the lib we are using for panel presentation. This resulted in always getting a 0 width view. 
Width of the content is now calculated directly using the container panel size.
> fix(ColorSelectionFloatingPanelViewController): Base sizing of collectionView on parent panel

- kDrive/UI/Controller/Menu/PhotoList/PhotoListViewController.swift
- kDrive/UI/Controller/Menu/PhotoList/PhotoListViewModel.swift
- kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
~~I could also batch refresh all `File`s on a pull to refresh, but a lot of work for limited impact.~~
Did the pull to refresh thing.
> fix: Only display in gallery items that can be displayed without refreshing File entity

- kDrive/AppRouter.swift
- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
Make sure it does not try to restore or save its state if data is invalid.
In some conditions, incorrect restoration data could be stored, resulting in a crash.
> fix(LaunchPanelsController): No restoration if in data is invalid

- kDrive/UI/Controller/Files/Categories/ManageCategoriesViewController.swift
- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController+Actions.swift
- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController+Actions.swift
- kDrive/UI/Controller/Files/RecentActivityFilesViewController.swift
- kDrive/Utils/FileActionsHelper.swift
A realm crash was in ManageCategoriesViewController. This class was tracking some live objects that can get invalidated.
Now it tracks frozen objects. And I made it explicit in the naming of init methods.
> fix: ManageCategoriesViewController now uses frozen files to prevent a crash

- kDrive/UI/View/Files/Preview/AudioCollectionViewCell.swift
- kDriveCore/AudioPlayer/MediaPlayerOrchestrator.swift
- kDriveCore/AudioPlayer/SingleTrackPlayer.swift
- kDriveCore/DI/FactoryService.swift
https://github.com/Infomaniak/ios-kDrive/issues/1011
comment `singleTrackPlayer.pause()` in `didEndDisplaying()`
> fix: Prevent two audio player to run at once

- kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
This is done trying to resolve a crash only seen on iOS18 for now.
> fix(DriveFileManager): Make sure liveFile.localContainerUrl is called once

- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
The action of the button circled in red now works
> fix: Close button works in share extension in SaveFileViewController

- kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
> fix(removeFileInDatabase): Fix stack overflow

- kDriveCore/Data/Api/DriveApiFetcher.swift
Already added since a long time on Mail. I think we forgot to add it on Drive.
> feat: Add RequestContextIdAdaptor to ApiFetcher

- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Models/FileActivity.swift
This PR addresses two issues in the FileActivityDetails:
- We only want to display a subset of the activities in the file details view. 
- Some of the activities we asked for were also invalid.
> fix: Pass correct activities for FileDetailsView

- kDriveFileProvider/FileProviderExtension+Thumbnail.swift
- kDriveFileProvider/FileProviderExtension.swift
Commit 1: Fix: Upload wasn't triggered if the file already existed in DB
Commit 2: Apple doc says we should return nil if there is no thumbnail
> fix: FileProvider upload already existing files + Correctly report missing thumbnail

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
- kDriveCore/Data/Models/Drive/Drive.swift
[edited] In some rare occurrence, the Drive object is invalidated and the `categories(for:` function breaks.
This is a workaround for that.
> fix(FileListViewController): Prevent realm crash in FileList

- kDrive/UI/Controller/Files/Upload/UploadQueueFoldersViewController.swift
- kDriveCore/DI/FactoryService.swift
- kDriveCore/Utils/AbstractLog+Category.swift
This PR only adds some logs if a rare orphan  `uploadFile` exists.
Will be done in a further PR: Remove orphan files in the background, as the root folder no longer exists.
> fix(OrphanFiles): Added a sentry

- kDriveCore/Data/Cache/DriveFileManager/DriveFileManager+Listing.swift
Try to modify a deleted realm object within the same transaction was crashing in some specific case.
> fix(DriveFileManager): In some specific case realm crash 

- kDriveFileProvider/Enumerators/DirectoryEnumerator.swift
Fetch was done with an ID of type Int where an UID of type String was expected as the primary key.
> fix(DirectoryEnumerator): Fetch object by UID with an actual UID

- kDriveCore/Data/Models/PartialListingResult.swift
`lastAction` could be null if older than X months
> fix: Allow null activity type offline

- kDrive/UI/Controller/Home/RootMenuHeaderView.swift
HomeView was crashing when showing UploadCell on some iOS versions. For some reason, `UICollectionViewLayoutInvalidationContext` is very hard and buggy to use. Switching from `invalidateDecorationElements` to `invalidateSupplementaryElements` seems to work without any side effect.
Fix for sentry short ids:
- KDRIVE-IOS-9Q7
- KDRIVE-IOS-8KX
> fix: Prevent NSInternalInconsistencyException when reloading header

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
> fix: Realm accessed from the wrong thread

- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
We can't upload files to the drive root anymore so it doesn't make sense to select it by default. Personal files is instead selected.
> fix: Prevent selecting "Drive root" and select "My personal files"

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
This PR resolves two issues with the header:
1. The title didn't update correctly after a sorting change. This is because of the recent PR to fix the empty view before this PR we were relying on the display empty view logic to update the header which wasn't a good idea. We are now updating the title after the file collection changes as before.
2. The grid or list icon button wasn't updating correctly this is probably because of changes in the collectionView layout on iOS 18. I updated the code to do something more in line with the collectionView apis.
> fix: Correctly display changes in files header

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController+Actions.swift
- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController+Actions.swift
- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
- kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
- kDriveCore/Data/Cache/DriveFileManager/DriveFileManagerConstants.swift
- kDriveCore/Data/Models/File.swift
- kDriveCore/Data/Models/Rights.swift
> fix: Multiple selection action not same between iOS and Android, plus fix color

- kDrive/UI/Controller/Menu/StorageTableViewController.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+UploadChunk.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation.swift
- kDriveCore/Data/UploadQueue/Queue/UploadQueue+Queue.swift
- kDriveCore/Data/UploadQueue/Servicies/FreeSpace/FreeSpaceService.swift
- Each chunk is now cleaned right away after a successful upload. In some heavy system load conditions, the clean-up was not performed.
- The clean-up of the cache folder is triggered earlier on
- The cleanup is not only done when the app closes, but now also before we try to rebuild the upload queue
> fix: Cache cleanup fix

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Menu/PhotoList/PhotoListViewController.swift
- kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
`FileListViewController` uses `displayedFiles` which is an array because there are no sections. 
`PhotoListViewController` extends `FileListViewController` but has a different datasource implementation with one section per month. This creates a mixup of indexes on selection.
This PR adds a `getDisplayedFile(at indexPath:IndexPath)` that can be overridden by subclasses for custom behaviour
> fix: Correctly select elements in gallery

- kDrive/Utils/FileActionsHelper.swift
A deeper refactor could be performed to explicit the use of frozen files in `File actions`.
Right now this will prevent a realm crash when using the `save` action.
> fix: Prevent a realm crash when saving a file

- kDrive/UI/Controller/Menu/Share/PublicShareViewModel.swift
- kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
With the fixed `ios-core`, passing the cursor wehre needed fixed the public shares not been able to _load more_
> fix(DriveFileManager): Fix pagination for public share

- kDriveCore/Data/UploadQueue/Queue/UploadQueue+Queue.swift
Prevent a crash by forcing the use of an Array instead of a lazy collection.
> fix(UploadQueue): Prevent an enumeration crash.

- kDrive/UI/Controller/Files/Save File/SaveFileViewController+FooterButtonDelegate.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController+SelectDriveDelegate.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController+SelectFolderDelegate.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController+SelectPhotoFormatDelegate.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController+UITableViewDataSource.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController+UITableViewDelegate.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
Split the class for better readability and further development.
Strictly compatible with the current code, does not change anything.
Required by `PublicShare` feature.
> refactor(SaveFileViewController): Split the class

- Tuist/Package.resolved
- Tuist/Package.swift
Library bump, given the unit tests on the library I'm confident it will work smoothly.
> chore: Bump swift-concurrency to 1.0.0

- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
- kDrive/UI/Controller/Menu/Share/PublicShareViewModel.swift
- kDrive/UI/View/Files/FileListBarButton.swift
- kDriveCore/Data/DownloadQueue/DownloadQueue.swift
Display an activity indicator while the download proceeds.
Can cancel a download all action with a tap.
root pr https://github.com/Infomaniak/ios-kDrive/pull/1349
> feat: External links download all progres UI

- kDriveCore/Data/UploadQueue/Servicies/PhotoLibraryUploader+Scan.swift
- kDriveCore/Utils/PHAsset/PHAssetIdentifier.swift
- kDriveCore/Utils/Sentry/SentryDebug+Upload.swift
- PhotoSync will skip an iCloud asset if Apple's API is in error. The scan will continue.
- Small changes on `Sentry` related code for better tracking of the issue.
> fix(PhotoSync): Skip iCloud asset on iCloud critical error

- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
- kDriveCore/Data/UploadQueue/Servicies/FreeSpace/FreeSpaceService.swift
Here is what it looks like in the rare event of not enough space before we try to launch a sync.
This is important for iCloud users, as we will be unable to fetch iCloud assets if there is no sufficient space on the device.
> fix(PhotoSync): Do not start if not enough free space available

- kDrive/AppRouter.swift
- kDrive/UI/Controller/LoginDelegateHandler.swift
> fix: Public Share works with app lock

- kDriveCore/Data/DownloadQueue/DownloadOperation/DownloadAuthenticatedOperation.swift
The assertion in invalid, when the download task is __cancelled__ we do not have a file at the end of the download.
It erroneously triggers with debug builds
> fix(DownloadAuthenticatedOperation): Remove invalid assertion in debug

- kDrive/Utils/AppFactoryService.swift
- kDriveCore/Utils/InExtensionRouter.swift
Like we discussed, trying to move away from the `if EXTENSION` model, I try to rely more on the DI framework.
Here in extension mode, some code path tries to call the `AppNavigable` protocol.
It does not exist currently in extension mode, and crashes. 
Having one is more elegant than #ifdef existing code.
I introduced an `InExtensionRouter` that does nothing.
> fix: InExtensionRouter availlable in extension mode to prevent crashes

- kDriveFileProvider/Enumerators/DirectoryEnumerator.swift
fix for KDRIVE-IOS-BWQ
If in the same action result the user has updated and deleted a file (eg. rename then delete). The fileprovider would crash because the updated file was invalidated. 
This PR removes the file from the updatedItems if its also in the deletedItems
> fix(DirectoryEnumerator): Remove deleted items from updated items

- kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
- kDrive/UI/View/Files/Upload/UploadTableViewCell.swift
When cancelling an upload, the app crashes.
`DiffKit` accesses an invalidated object and crashes.
The `UploadQueueViewController` now tracks a list of frozen files.
The cell was updated to use frozen files as input.
The use of frozen or live file was explicited
> fix: Invalidated live object crash DiffKit while diffing

- Tuist/Package.resolved
- Tuist/Package.swift
Issue was a DI property wrapper (LazyInjectService) was _not_ thread safe.
https://github.com/Infomaniak/swift-dependency-injection/pull/10
> fix(ActionExtension): Fix a race condition in DI library

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/View/Files/FloatingPanel/FloatingPanelActionCollectionViewCell.swift
- kDrive/UI/View/Files/FloatingPanel/FloatingPanelActionCollectionViewCell.xib
> feat(FloatingPanelActionCollectionViewCell): Chip capability

- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/MykSuiteRestrictions.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareAndRightsViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareLinkSettingsViewController.swift
- kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkSettingTableViewCell.swift
- kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkSettingTableViewCell.xib
- kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkTableViewCell.swift
Feature branch https://github.com/Infomaniak/ios-kDrive/pull/1405
> feat: Public share quota, advanced settings chip

- kDriveCore/Data/UploadQueue/Queue/UploadQueue+Queue.swift
- kDriveCore/Data/UploadQueue/Servicies/PhotoLibraryUploader+Scan.swift
- kDriveCore/Data/UploadQueue/Servicies/PhotoLibraryUploader.swift
When we re-scan the photo library, we do not exclude what is already in queue.
Therefore, we can end up with multiple uploads of the same file in upload queue.
This PR aims at solving this issue by checking if the hash of the file is queued.
Also, some preventive steps were taken to prevent collisions during the scan of the photo library.
Needed by the 4G feature https://github.com/Infomaniak/ios-kDrive/pull/1440
> fix: Prevent photo library from duplicating items in the upload queue

- kDriveCore/Utils/Sentry/SentryDebug+Upload.swift
Casting NSNotFound (a large Int64 on 64bit arch, 32 in 32bit mode) into Int32 was crashing.
This removes the need for a NSNotFound, and still has a meaningful value that is not zero when not set.
> fix: Remove and int overflow crash

- kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
Using DiffKit built in types allows us to animate the error cell, rounded corners and the correct list of files.
Root PR https://github.com/Infomaniak/ios-kDrive/pull/1440
> feat(UploadQueueViewController): Section support using DiffKit

- TestFlight/WhatToTest.en-GB.txt
- TestFlight/WhatToTest.fr-FR.txt
Version in Tuist config is already bumped to `5.3.0`
> chore: Release build 5.3.0-b1

- kDrive/UI/Controller/Files/Categories/EditCategoryViewController.swift
- kDrive/UI/Controller/Files/DropBox/ManageDropBoxViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/InviteUserViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareLinkSettingsViewController.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController+FooterButtonDelegate.swift
- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
- kDrive/UI/Controller/NewFolder/NewFolderViewController.swift
- kDrive/UI/Controller/Photo/SavePhotoViewController.swift
- kDrive/UI/Controller/Scan/SaveScanViewController.swift
- kDrive/UI/View/Footer view/FooterButtonView.swift
Two steps
- Mini refactor to explicit that `FooterButtonDelegate` always callback with a `IKLargeButton`
- Apply the button state in the required view
> fix: Set save button loading while the photo sync settings are saving

- Tuist/Package.resolved
- Tuist/Package.swift
Having a discrete PR for this is a good reference point to track if any issue and/or performance improvements from the Lock based DI.
> chore: Bump DI to the version using an internal lock

- kDrive/UI/Controller/Menu/ParameterTableViewController.swift
With a `myKsuite` account, the settings screen will crash in beta only. Easy to reproduce.
> fix: Incorrect cell count

- kDriveFileProvider/FileProviderExtension.swift
`UploadService` no longer exists within DI, we must use `UploadServiceable`
Somehow this one was missed in a recent refactor.
> fix(FileProviderExtension): Resolve correct DI type

- kDrive/UI/Controller/Files/Save File/SelectFolderViewController.swift
Using inherited property `displayedFiles` to make sure we have a data source that reflects the view to prevent a crash
> fix: Crash on force unwrap

- kDrive/UI/Controller/Files/FilePresenter.swift
Some navigation code that (I suspect) broke with the APIV3 migration was the culprit.
Fixes https://github.com/Infomaniak/ios-kDrive/issues/1335
> fix(FilePresenter): Function presentParent works again

- kDrive/UI/View/Files/Preview/CodePreviewCollectionViewCell.swift
Large text files will crash the app for memory over usage, and corrupted files never complete.
I managed to Swiftify the current code, reduce drastically memory usage. 
But I still had an issue with the JS preview library. So I capped the max size to be previewed.
> fix: Text preview of large or corrupted files crashes

- kDrive/Resources/Assets.xcassets/Colors/onlyOfficeBackgroundColor.colorset/Contents.json
- kDrive/UI/Controller/Files/OnlyOfficeViewController.swift
Prevent the webview to extend on safe areas to fix a glitch in dark mode
Here is a before:
And after:
> fix(OnlyOfficeViewController): Fix status bar dark mode in OnlyOffice

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController+Actions.swift
- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareAndRightsViewController.swift
- kDrive/UI/Controller/NewFolder/NewFolderViewController.swift
- kDrive/UI/View/Files/FloatingPanel/FloatingPanelActionCollectionViewCell.swift
- kDriveCore/Data/Cache/DriveFileManager/DriveFileManager+AvailableOffline.swift
- kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
- Reworked `FileActionsFloatingPanelViewController` to function with frozen objects instead of live ones internally.
- Reworked `setFile()` function to work consistently given any input realm object in any state.
- Previously, given an entry point, the behaviour could be dissimilar.
- Fix an issue with an invalidated `live` object, since it works with frozen objects internally now.
- In production, it is relatively easy to glitch the "available offline" function. This is now way more robust.
> fix: Realm crash on invalidated object in File action sheet

- kDrive/AppDelegate.swift
- kDriveCore/Utils/Sentry/SentryDebug.swift
A clean-up can take time at the termination of the app. 
Here I add breadcrumbs to be able to track issues Sentry side.
> chore: Added breadcrumbs on app termination to track a bug

- kDrive/UI/Controller/Files/OnlyOfficeViewController.swift
Had to clear the cache when creating a webView to force the correct theme color to be applied.
> fix: OnlyOffice theme is the correct OS theme when editing a document

- kDriveCore/Services/BackgroundTasksService.swift
I found a bug where the `background upload` feature can trigger while the app is running in the foreground. 
This tends to be while the app is running long photo sync uploads.
When the `background upload` is _then_ asked by the system to suspend, the uploads are frozen without the ability to restart without killing the app.
This PR simply reschedule the background task later, and exit gracefully.
> fix: Background refresh can freeze uploads in foreground

- kDriveCore/Data/Upload/Servicies/UploadService/Parallelism/UploadParallelismOrchestrator.swift
- kDriveCore/Data/Upload/Servicies/UploadService/Parallelism/WorkloadParallelismHeuristic.swift
When the app is in `background` or `innactive` the limit for memory usage is lower.
In order to stay alive, it is best to reduce uploads on these states.
I now track app state in order to modulate upload parallelism, and prevent app from crashing.
> fix: Reduce upload memory footprint when app is not active

- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
New installs defaults to WIFI only for photo sync.
Migration in unchanged.
> feat: Photo sync default to wifi only on new installs

- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
Pull to refresh no longer display empty view on offline folder when non empty
> fix: Correct empty view display logic

- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
On a clean install, the Wi-Fi only setting was set in base, not in UserDefaults.
> fix: Correctly set isWifiOnly default value in user defaults on clean install

- kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
- kDrive/UI/View/Files/Upload/UploadTableViewCell.swift
- kDriveCore/Data/Cache/PhotoSyncSettings.swift
- kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader+Sync.swift
- kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader.swift
`UploadQueueViewController` had issues working with sync settings from Realm (instead of user defaults).
This PR aims at observing the settings in order to work seamlessly with settings when they get updated.
> fix: Crash in upload queue view controller

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
> fix: Download action loading state was incorrect

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
On a first download and display of a PDF there was a scroll performance issue.
By correctly setting things up like when loading from local cache it just works.
> fix: Correctly setup observation in order to prevent a performance issue

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
- kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader+Scan.swift
Hashing media assets during photo sync scan can take a long time.
This is performed inside a batched DB transaction. 
This locks the DB in write for the time of a batch of 100 files.
Any write operation on this realm somewhere else will be locking.
Eg. If a user tries to edit sync settings during a batch scan, it can lock the main queue, to a point where the OS will kill the app.
Here I remove completely the DB write batching for the photo sync.
`UploadFile`s are added one by one.
I just make sure the UI correctly `throttle` display and refresh of the views. 
Most screens were already ready for this.
Upload progress is tracked by cell, so it is unchanged by added `throttle` operations
Diffkit calls are unchanged in lists, `throttle` is applied beforehand.
CPU usage is mostly unchanged …
> refactor: Removed photo scan batching

- kDrive/AppRouter.swift
- kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
- kDrive/UI/Controller/Home/RootMenuHeaderView.swift
- kDrive/UI/Controller/LaunchPanelsController.swift
- kDrive/UI/Controller/Menu/MenuViewController.swift
- kDrive/UI/Controller/Menu/ParameterTableViewController.swift
- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
- kDriveCore/DI/FactoryService.swift
- kDriveCore/Data/Cache/AccountManager.swift
- kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryCleanerService.swift
- kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader+Query.swift
- kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader+Scan.swift
- kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader+Sync.swift
- kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader.swift
- kDriveCore/Data/Upload/UploadQueue/Operation/UploadOperation+Error.swift
- kDriveCore/Data/Upload/UploadQueue/Operation/UploadOperation.swift
- kDriveCore/Data/Upload/UploadQueue/Queue/PhotoUploadQueue.swift
- kDriveCore/Services/BackgroundTasksService.swift
- kDriveCore/Utils/Logging.swift
- kDriveTestShared/MCKPhotoLibraryQueryable.swift
- kDriveTestShared/MCKPhotoLibraryScanable.swift
- kDriveTestShared/MCKPhotoLibrarySyncable.swift
- kDriveTestShared/MCKPhotoLibraryUploadable.swift
- kDriveTestShared/MockingHelper.swift
- kDriveTests/kDrive/Launch/ITAppLaunchTest.swift
- kDriveTests/kDriveCore/Files/UTPHAssetNameProvider.swift
Tests are flaky since an object can be missing in DI during tests
I created protocols around the already divided class `PhotoLibraryUploader`
Using DI I was able to register mocks of the `PhotoLibraryUploader` where needed
Both app and tests are no longer resolving directly the concrete type `PhotoLibraryUploader`
> fix: Missing PhotoSync object in DI in tests

- kDriveCore/Data/Models/Upload/UploadFile.swift
I limit fetched assets to one as we only use the first one
> fix: Limit fetch querry to first one

- kDrive/UI/Controller/Files/Search/SearchFiltersViewController.swift
- kDrive/UI/Controller/FloatingPanelSelectOptionViewController.swift
Small PR that fixes an issue on modern iPhones or sheets with too many options appearing under the notch.
> fix: Replace floating panel by sheet

- kDrive/UI/Controller/Files/Save File/LocationFolderViewController.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController+UITableViewDelegate.swift
- kDrive/UI/Controller/Files/Save File/SelectFolderViewController.swift
- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
- Rebuild hierarchy on move
- Start from root when saving file or selecting sync folder for photos
- Prevent showing non writable directories in recent
> fix: Folder selection improvements

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/View/Files/Preview/VideoCollectionViewCell.swift
- kDriveCore/VideoPlayer/VideoPlayer.swift
Hide play button when video can't be played
This PR fixes an issue where the play button was still shown even if the video couldn't be played. Now, the play button is hidden in such cases.
> fix: Handle incompatible videos

- kDrive/AppRouter.swift
- kDrive/UI/Controller/Files/Save File/SelectDriveViewController.swift
- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
- kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryCleanerService.swift
- kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader+Scan.swift
- kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader+Sync.swift
- kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader.swift
- kDriveCore/Data/Upload/Servicies/UploadService/UploadService+Datasource.swift
- kDriveCore/Data/Upload/Servicies/UploadService/UploadService.swift
- kDriveCore/Data/Upload/UploadQueue/Queue/KeyedUploadOperationable.swift
- kDriveCore/Data/Upload/UploadQueue/Queue/PhotoUploadQueue.swift
- kDriveCore/Data/Upload/UploadQueue/Queue/UploadQueue+Queue.swift
- kDriveCore/Data/Upload/UploadQueue/Queue/UploadQueue.swift
- kDriveCore/Data/Upload/UploadQueue/Queue/UploadQueueable.swift
- kDriveCore/Services/BackgroundTasksService.swift
- kDriveTestShared/MCKPhotoLibraryScanable.swift
Change drive OR disable photo sync will make the app forget about uploaded assets.
Other changes that were needed
- The initial scan process is now cancellable.
- The photoUploadQueue now can be purged, and behaves correctly when we reset the photo uploads.
> fix: Delete photos in realm when we change drive for sync

- kDriveCore/Data/Upload/UploadQueue/Chunk/RangeProvider.swift
- kDriveCore/Data/Upload/UploadQueue/Operation/UploadOperation+Error.swift
- kDriveCore/Data/Upload/UploadQueue/Operation/UploadOperation+UploadSession.swift
- kDriveCore/Data/Upload/UploadQueue/Operation/UploadOperation.swift
- kDriveCore/Data/Upload/UploadQueue/Operation/UploadOperationable.swift
- kDriveCore/Data/Upload/UploadQueue/Queue/UploadQueue+Queue.swift
- kDriveCore/Data/Upload/UploadQueue/Queue/UploadQueue.swift
This PR enables direct upload for small files (under 5Mib).
This brings performance improvements and reduces energy consumption by drastically reducing upload overhead.
Benefits may differ given the average size of files uploaded.
> feat: Small file direct upload

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/Controller/Files/SidebarViewController.swift
I now make sure that we only try to present the faulty View Controller when it is not already been presented.
Also, the content of the `SidebarViewController` was not correctly updated when switching size class on iPad (resizing window)
> fix: Prevent presentation issues on iPad

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
The local stored realm object could also be invalidated, I also make sure to keep a frozen version.
> fix: Realm crash invalidation

- kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader+Scan.swift
- kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader.swift
This works since the recent refactors.
- `uploadService.rebuildUploadQueue()` is costly, so I designed something that would not spam it.
- In background mode, we rely on a synchronous execution of the scan then the upload. 
- In background, the app continues to behave like it does today in production.
> feat: Early upload start during a photo sync
