- kDrive/UI/View/Files/FileCollectionViewCell.swift
Signed-off-by: Elena Willen <elena.willen@infomaniak.com>
> fix bug cell disabledView in dark mode

- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
- kDrive/UI/Controller/Photo/PhotoPickerDelegate.swift
- kDrive/UI/Controller/Scan/ScanNavigationViewController.swift
Scan: fileName begin with date for sorting
> t940-add date for scan fileName

- kDrive/UI/Controller/Menu/PhotoListViewController.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
Fix search by adding files to Realm
> [T947] Fix previews not working from search

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/Files/FileListCollectionViewController.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
- kDrive/UI/Controller/Files/Search/SearchFileViewController.swift
- kDrive/UI/Controller/Floating Panel Information/UpdateFloatingPanelViewController.swift
- kDrive/UI/Controller/Menu/AppLockSettingsViewController.swift
- kDrive/UI/Controller/Menu/NotificationsSettingsTableViewController.swift
- kDrive/UI/Controller/Menu/ParameterTableViewController.swift
- kDrive/UI/Controller/MigrationViewController.swift
- kDrive/UI/Controller/OnboardingViewController.swift
- kDrive/UI/View/Files/Upload/UploadTableViewCell.swift
- kDriveCore/Data/Api/DownloadQueue.swift
- kDriveCore/Data/Cache/AccountManager.swift
- kDriveCore/Data/Cache/DriveInfosManager.swift
- kDriveCore/Data/Models/Drive.swift
- kDriveCore/Data/Models/ListStyle.swift
- kDriveCore/Data/UploadQueue/UploadQueue.swift
- kDriveCore/Migration/MigrationHelper.swift
- kDriveCore/Utils/DriveUserDefaults+Extension.swift
- kDriveCore/Utils/NotificationsHelper.swift
- Refactor User Defaults
- Remember last upload location in save file
> [T951] Remember upload location

- kDrive/UI/Controller/Files/Search/SearchFileViewController.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
Fix crash in search and small adjustements (thanks to @Lnamw for her help)
> Hotfix: crash in search

- kDrive/UI/View/Files/FileDetail/ShareLink/InviteUserTableViewCell.swift
> inviteUser dropdown fixed

- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/UploadQueue/FileUploader.swift
Reduce number of Realm created in DriveFileManager
> WIP: DriveFileManager Realm

- kDrive/UI/View/Files/FileDetail/ShareLink/MessageTableViewCell.swift
> inviteUser textField fixed

- kDrive/UI/Controller/Menu/PhotoListViewController.swift
> photoList navigationBar fixed

- kDriveCore/Data/Models/DriveError.swift
Fix localized description for DriveError
> [T967] Fix localized description for DriveError

- kDrive/UI/Controller/MainTabViewController.swift
Check right when switching tab
> [T964] Fix plus button rights

- kDrive/UI/Controller/Files/Search/Search.storyboard
> searchViewController scroll fixed

- kDrive/UI/View/Files/FloatingPanel/FloatingPanelTableViewCell.swift
crash fixed by Florentin while "pair debugging" on my machine
> fix crash download

- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
- Update save button when changing drive
- Fixing default file name
> [T952] Fix file name + update button

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/View/Files/Preview/NoPreviewCollectionViewCell.swift
> download preview error added

- kDrive/UI/Controller/Files/Files.storyboard
- kDrive/UI/Controller/Menu/Trash/TrashFloatingPanelTableViewController.swift
- kDrive/UI/View/Files/DropBox/DropBoxLinkTableViewCell.xib
- kDrive/UI/View/Files/FileDetail/ShareLink/InvitedUserTableViewCell.xib
- kDrive/UI/View/Files/FileDetail/ShareLink/MessageTableViewCell.xib
- kDrive/UI/View/Files/FileDetail/ShareLink/RightsSelectionTableViewCell.swift
- kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkAccessRightTableViewCell.xib
- kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkSettingTableViewCell.swift
- kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkSettingTableViewCell.xib
- kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkTableViewCell.xib
- kDrive/UI/View/Files/FloatingPanel/FloatingPanelCollectionViewCell.xib
- kDrive/UI/View/Header view/FilesHeaderView.xib
- kDrive/UI/View/Menu/SwitchUser/UsersDropDownTableViewCell.xib
- kDrive/UI/View/NewFolder/NewFolderLocationTableViewCell.xib
fix dark mode bugs through the app
> T959 dark mode

- kDrive/UI/View/Files/FileCollectionViewCell.swift
- kDrive/UI/View/Files/FileCollectionViewCell.xib
> fix fileCell highlightedView

- kDrive/UI/Controller/Favorite/FavoriteCollectionViewController.swift
- kDrive/UI/Controller/Menu/LastModificationsViewController.swift
- kDrive/UI/Controller/Menu/PhotoListViewController.swift
- kDrive/UI/Controller/Menu/SharedWithMe/SharedDrivesViewController.swift
- kDrive/UI/Controller/Menu/Trash/TrashCollectionViewController.swift
- kDrive/UI/View/EmptyTableView/EmptyTableView.swift
- kDrive/UI/View/EmptyTableView/EmptyTableViewCell.swift
Improve offline UI on the following views:
- Photo list
- Shared drives
- Trash
- Last modifications
- Trash
> [T963] Improve offline UI

- kDriveCore/Data/Cache/DriveInfosManager.swift
Signed-off-by: Philippe Weidmann <philippe.weidmann@infomaniak.com>
> Only remove / add necessary domains

- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/View/Files/FileDetail/FileDetailActivitySeparatorTableViewCell.swift
- kDrive/UI/View/Files/FileDetail/FileDetailActivitySeparatorTableViewCell.xib
> refactor fileDetailActivitySeparatorCell

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/DriveErrorViewController.swift
- kDrive/UI/Controller/Menu/SharedWithMe/SharedDrivesViewController.swift
- kDrive/UI/Controller/Menu/SwitchUserViewController.swift
- kDrive/UI/Controller/OnboardingViewController.swift
- kDriveCore/Data/Cache/AccountManager.swift
- kDriveCore/Data/Models/DriveError.swift
Display maintenance views from login and sharedWithMe
> T936 drive maintenance

- kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/Save File/SelectFolderViewController.swift
> moveFile fixed

- kDrive/UI/View/Files/SwipableCell.swift
> swipableCell fixed

- kDrive/UI/Controller/Files/RecentActivityFileListViewController.swift
Fix recent activity file list corners after sorting
> Fix recent activity file list corners

- kDrive/UI/Controller/Menu/Trash/TrashCollectionViewController.swift
> loadingIndicator added to trash

- kDriveCore/Data/Cache/DriveFileManager.swift
Fix a bug where moving a file set as available offline would not be marked as available offline anymore after the move operation
> [T1020] Fix move offline file

- kDrive/UI/Controller/Files/SelectFloatingPanelTableViewController.swift
- kDrive/UI/View/Files/FloatingPanel/FloatingPanelTableViewCell.swift
- kDrive/UI/View/Files/FloatingPanel/FloatingPanelTableViewCell.xib
Disable available offline action for folders-only selection in multiple selection floating panel
> Disable available offline action for folders-only selection

- kDrive/UI/Controller/Files/FileListViewController.swift
Pop file list if folder has been deleted
Fixes #93
> Update UI after remote folder deletion

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
> Fix crash when reloading PDF preview cell

- kDrive/UI/Controller/Menu/PhotoListViewController.swift
- kDrive/UI/View/Files/FileCollectionViewCell.xib
- Fix file cell margin
- Fix photo list
> Small UI fixes

- kDrive/UI/Controller/Home/HomeTableViewController.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
> Fix crash in home when switching drive

- kDrive/AppDelegate.swift
> Fix a bug when uploading open-in-place files

- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
- kDriveCore/Data/UploadQueue/PhotoLibraryUploader.swift
- kDriveCore/Data/UploadQueue/UploadQueue.swift
- Prevent photo sync to be disabled (fixes #97)
- Small fixes related to photo sync settings
> Sync settings fix

- kDrive/UI/Controller/Files/FileListViewController.swift
- kDrive/UI/Controller/Menu/MenuViewController.swift
- kDrive/UI/Controller/Menu/Trash/TrashViewController.swift
- Fix trash update after restoration
- Prevent inconsistent drive file manager
> State restoration improvements

- kDrive/UI/Controller/Home/HomeTableViewController.swift
> issue69 fixed

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
Fixes #130:
- Use live `File` in quick actions panel to always be up-to-date
- Re-download file is version is too old
- Dismiss interaction controller after editing
- Update file information after upload
> Fix file not updating when editing it with open-in-place

- kDrive/UI/Controller/Files/FileDetailViewController.swift
- Build file detail rows based on available data
- Fix bug where file could be nil
> Refactor file detail to improve rows and fix bug

- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
Use loadFileRepresentation for all item providers to fix dates on file import
> Fix creation/modification date on file import

- kDrive/UI/Controller/Files/Rights and Share/ShareAndRightsViewController.swift
- kDrive/UI/Controller/Menu/LastModificationsViewController.swift
- kDrive/UI/Controller/Menu/MySharesViewController.swift
- kDrive/UI/Controller/Menu/Trash/TrashViewController.swift
- kDrive/UI/Controller/RecentActivitySharedController.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Cache/AccountManager.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/UploadQueue/UploadOperation.swift
- kDriveFileProvider/FileProviderEnumerator.swift
- kDriveFileProvider/FileProviderExtension+Actions.swift
> Shared ApiFetcher for each account

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/View/Files/Preview/PdfPreviewCollectionViewCell.swift
> PDF preview improvements

- kDrive/AppDelegate.swift
- kDriveCore/Data/UploadQueue/PhotoLibraryUploader.swift
- Add confirmation modal before photo deletion
- Add check for delete settings
> Add confirmation modal and improve photo deletion

- kDrive/UI/Controller/Files/FileListViewController.swift
- kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
- kDrive/UI/View/Files/Upload/UploadTableViewCell.swift
- kDriveCore/Data/Cache/AccountManager.swift
- kDriveCore/Data/Cache/BackgroundRealm.swift
- kDriveCore/Data/Cache/DriveInfosManager.swift
- kDriveCore/Data/UploadQueue/UploadOperation.swift
- kDriveCore/Data/UploadQueue/UploadQueue.swift
- kDriveCore/Utils/Throttler.swift
- Prevent memory issues, deadlocks and data race in upload queue
- Introduce throttling in the file list to prevent too many reloads (still some crashes to investigate later)
> Improve upload queue

- kDrive/UI/Controller/Menu/PhotoListViewController.swift
- kDrive/UI/Controller/Menu/Trash/TrashViewController.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- Format files
- Fix retaining issue in trash
> Format files & fix trash issue

- kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
- kDrive/UI/View/Files/FloatingPanel/FloatingPanelCollectionTableViewCell.swift
- kDrive/UI/View/Files/FloatingPanel/FloatingPanelCollectionViewCell.swift
- kDrive/UI/View/Files/FloatingPanel/FloatingPanelCollectionViewCell.xib
- kDrive/UI/View/Files/FloatingPanel/FloatingPanelTableViewCell.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
> Download file

- kDriveCore/Utils/Constants.swift
> fixed file relativeTime

- kDrive/UI/View/Files/FloatingPanel/FloatingPanelCollectionViewCell.swift
- kDrive/UI/View/Files/FloatingPanel/FloatingPanelTableViewCell.swift
> fix fileQuickAction download

- kDrive/UI/View/Home/RecentActivityTableViewCell.swift
> recentActivity fixed

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/SelectFloatingPanelTableViewController.swift
- kDriveCore/Data/Api/ApiRoutes.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/Models/FileActivity.swift
- kDriveCore/Utils/DriveUserDefaults+Extension.swift
> Update offline files improvements

- kDrive/UI/View/Files/Preview/DownloadingPreviewCollectionViewCell.swift
- kDriveCore/Data/Models/File.swift
> Add animated GIF support in preview

- kDrive/UI/Controller/Floating Panel Information/InformationFloatingPanel.storyboard
- kDrive/UI/View/Files/DropBox/DropBoxLinkTableViewCell.xib
- kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkTableViewCell.xib
> Fix links font

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/Base.lproj/Main.storyboard
- kDrive/UI/Controller/Floating Panel Information/AccessFileFloatingPanelViewController.swift
- kDrive/UI/Controller/Floating Panel Information/DriveMaintenanceFloatingPanelViewController.swift
- kDrive/UI/Controller/Floating Panel Information/DropBoxFloatingPanelViewController.swift
- kDrive/UI/Controller/Floating Panel Information/InformationFloatingPanel.storyboard
- kDrive/UI/Controller/Floating Panel Information/InformationFloatingPanelViewController.swift
- kDrive/UI/Controller/Floating Panel Information/MigratePhotoSyncSettingsFloatingPanelViewController.swift
- kDrive/UI/Controller/Floating Panel Information/NoAccessFloatingPanelViewController.swift
- kDrive/UI/Controller/Floating Panel Information/SavePhotosFloatingPanelViewController.swift
- kDrive/UI/Controller/Floating Panel Information/SecureLinkFloatingPanelViewController.swift
- kDrive/UI/Controller/Floating Panel Information/ShareFloatingPanelViewController.swift
- kDrive/UI/Controller/Floating Panel Information/UnsupportedExtensionFloatingPanelViewController.swift
- kDrive/UI/Controller/Floating Panel Information/UpdateFloatingPanelViewController.swift
- kDrive/UI/View/Home/RecentActivityCollectionViewCell.xib
- Fix some warnings in XIB and storyboards
- Fix issues related to information floating panels
> Fix IB warnings

- kDrive/AppDelegate.swift
- kDriveCore/Data/Cache/AccountManager.swift
- kDriveCore/Utils/KeychainHelper.swift
Move keychain methods to KeychainHelper.swift
Update keychain item instead of deleting and readding updated item afterwards
> Refactor keychain + Update instead of Delete & Add

- kDrive/UI/Controller/Files/DropBox/ManageDropBoxViewController.swift
- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareAndRightsViewController.swift
- kDrive/UI/Controller/Floating Panel Information/InformationFloatingPanel.storyboard
- kDrive/UI/Controller/Floating Panel Information/InformationFloatingPanelViewController.swift
- kDrive/UI/View/Files/DropBox/DropBoxLinkTableViewCell.swift
- kDrive/UI/View/Files/DropBox/DropBoxLinkTableViewCell.xib
- kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkTableViewCell.swift
- kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkTableViewCell.xib
> replace copy shareLink with share shareLink

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/Controller/Home/HomeTableViewController.swift
- Fix a crash in home
- Fix a crash in preview
> Fix crashes

- kDriveCore/Utils/FileImportHelper.swift
> Fix string import

- kDrive/UI/Controller/OnboardingViewController.swift
- kDriveCore/Data/Cache/AccountManager.swift
> Handle case when user only has shared drives

- .package.resolved
- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/Controller/Files/FileListViewController.swift
- kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareAndRightsViewController.swift
- kDrive/UI/Controller/Files/Save File/SelectFolderViewController.swift
- kDrive/UI/Controller/Files/SelectFloatingPanelTableViewController.swift
- kDrive/UI/Controller/MainTabViewController.swift
- kDrive/UI/View/Files/FileDetail/ShareLink/UsersAccessTableViewCell.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/DownloadQueue/DownloadQueue.swift
- kDriveCore/Data/Models/ApiResponse.swift
- kDriveCore/Data/Models/Comment.swift
- kDriveCore/Data/Models/Drive.swift
- kDriveCore/Data/Models/DriveError.swift
- kDriveCore/Data/Models/DriveUser.swift
- kDriveCore/Data/Models/File.swift
- kDriveCore/Data/Models/FileActivity.swift
- kDriveCore/Data/Models/PhotoSortMode.swift
- kDriveCore/Data/Models/Rights.swift
- kDriveCore/Data/Models/SharedFile.swift
- kDriveCore/Data/Models/Tag.swift
- kDriveCore/Data/Models/UploadFile.swift
- kDriveCore/Data/Models/UploadToken.swift
- kDriveCore/Utils/FileImportHelper.swift
- kDriveFileProvider/FileProviderItem.swift
**Warning**: Must test before merging
> Upgrade & refactor models

- kDrive/AppDelegate.swift
- kDriveCore/Data/Cache/DriveInfosManager.swift
> Clean File Provider domains on first launch

- Project.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Utils/ReachabilityListener.swift
> Background task refresh token

- kDrive/UI/Controller/Files/Rights and Share/InviteUserViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/RightsSelectionViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareAndRightsViewController.swift
- kDrive/UI/View/Files/FileDetail/ShareLink/InviteUserTableViewCell.swift
- kDrive/UI/View/Files/FileDetail/ShareLink/InvitedUserTableViewCell.swift
- Support for return key in add user text field
- Fixes in invite user view
- Refactor code
> Refactor share flow to harmonize with Android

- kDrive/UI/Controller/Files/SelectFloatingPanelTableViewController.swift
> Fix document picker dismiss in selection panel

- kDrive/UI/Controller/Files/DropBox/ManageDropBoxViewController.swift
- kDrive/UI/View/Files/FileDetail/FileDetailActivityTableViewCell.swift
- kDrive/UI/View/NewFolder/NewFolderSettingsTableViewCell.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/Models/FileActivity.swift
> Fix manage drop box

- kDrive/UI/Controller/Files/FileListViewController.swift
- kDrive/UI/Controller/Files/Search/SearchViewController.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/Models/DriveError.swift
> Fix search

- kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
> Fix object invalidated error

- kDriveCore/Data/MQService/MQService.swift
Improve MQService reconnect based on web app
> Improve MQService reconnect

- kDrive/UI/Controller/NewFolder/NewFolderViewController.swift
- kDrive/UI/View/NewFolder/NewFolderLocationTableViewCell.swift
- kDrive/UI/View/NewFolder/NewFolderLocationTableViewCell.xib
- kDrive/UI/View/NewFolder/NewFolderShareRuleTableViewCell.swift
> Fix create folder

- kDriveCore/Utils/FileImportHelper.swift
> Fix bug when uploading to a different account

- Project.swift
> Fix animations in extensions

- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/Controller/Files/FileListViewController.swift
- kDrive/UI/Controller/Files/FilePresenter.swift
- kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/RightsSelectionViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareLinkSettingsViewController.swift
- kDrive/UI/Controller/Menu/PhotoListViewController.swift
- kDrive/UI/Controller/Menu/SharedWithMe/SharedDrivesViewController.swift
- kDrive/UI/Controller/NewFolder/NewFolderTypeTableViewController.swift
- kDrive/UI/View/Files/FileDetail/ShareLink/InvitedUserTableViewCell.swift
> Fix closure captures

- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
- kDriveCore/Data/UploadQueue/UploadQueue.swift
- kDriveCore/Utils/DriveUserDefaults+Extension.swift
> Save user id to fix last location in extensions

- kDriveCore/Data/Api/ApiRoutes.swift
- kDriveCore/Data/Models/FileActivity.swift
> Workaround to prevent crashes related to FileActivityType

- kDrive/UI/Controller/Files/FileListViewController.swift
- kDrive/UI/Controller/Files/Files.storyboard
- kDrive/UI/Controller/Files/Upload/UploadQueueFoldersViewController.swift
- kDrive/UI/Controller/Home/HomeTableViewController.swift
- kDrive/UI/View/Files/FileCollectionViewCell.swift
- kDrive/UI/View/Files/FloatingPanel/FloatingPanelCollectionViewCell.swift
- kDrive/UI/View/Files/FloatingPanel/FloatingPanelTableViewCell.swift
- kDrive/UI/View/Files/Upload/RPCircularProgress.swift
- kDrive/UI/View/Files/Upload/UploadFolderTableViewCell.swift
- kDrive/UI/View/Files/Upload/UploadFolderTableViewCell.xib
- kDrive/UI/View/Files/Upload/UploadTableViewCell.swift
- kDrive/UI/View/Header view/FilesHeaderView.swift
- kDrive/UI/View/Home/InsufficientStorageTableViewCell.swift
- kDrive/UI/View/Home/UploadsInProgressTableViewCell.swift
- kDrive/UI/View/Home/UploadsInProgressTableViewCell.xib
- kDrive/Utils/UploadCountManager.swift
- kDriveCore/Data/UploadQueue/UploadQueue.swift
Fixes #289 
Will add it to the menu after merging the refactor from the in-app purchases branch
> New upload in progress view

- kDriveTests/DriveApiTests.swift
- kDriveTests/Env.swift
- Fix tests
- Add a unit test for teams
> Fix tests + add team rights test

- kDrive/UI/Controller/Files/FileListViewController.swift
- kDrive/UI/Controller/MainTabViewController.swift
- kDrive/UI/Controller/Menu/Menu.storyboard
> Show tab bar in shared with me

- kDrive/UI/Controller/NewFolder/NewFolderTypeTableViewController.swift
- kDrive/UI/Controller/NewFolder/NewFolderViewController.swift
> Refactor new folder workflow to improve support of shared with me

- kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
> Fix wrong favorite snackbar

- kDrive/UI/Controller/Files/FileListViewController.swift
- kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/MultipleSelectionViewController.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
- kDrive/UI/Controller/Files/Save File/SelectFolderViewController.swift
- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
- kDrive/UI/Controller/Menu/Trash/TrashViewController.swift
> Select folder improvements

- kDrive/UI/Controller/Files/FileListViewController.swift
- kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/MultipleSelectionViewController.swift
- kDrive/UI/Controller/Files/SelectFloatingPanelTableViewController.swift
- kDriveCore/Data/Api/ApiRoutes.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/MQService/ActionType.swift
> Copy in multi-selection

- .package.resolved
- kDrive/IAP/StoreRequest.swift
- kDrive/UI/Controller/MainTabViewController.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/Models/File.swift
- kDriveCore/Utils/ParameterEncoder+Extension.swift
- kDriveCore/Utils/Throttler.swift
- kDriveTests/DriveApiTests.swift
Fixes #329 + other improvements
> Refactor drive api fetcher

- kDrive/UI/View/Files/FileCollectionViewCell.swift
> Fix download cancel in file cell

- kDriveCore/Data/UploadQueue/UploadQueue.swift
> Add uploads with non-existent session to queue

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/Menu/Menu.storyboard
- kDrive/UI/Controller/Menu/ParameterTableViewController.swift
- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
- kDrive/UI/Controller/MigrationViewController.swift
- kDrive/UI/View/Footer view/FooterButtonView.xib
> Photo sync settings improvements

- kDriveCore/Data/Api/ApiRoutes.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/Models/UploadFile.swift
- kDriveCore/Data/UploadQueue/PhotoLibraryUploader.swift
- kDriveCore/Data/UploadQueue/UploadQueue.swift
> Conflict options | Fix for #158

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/View/Files/Preview/ImagePreviewCollectionViewCell.swift
- kDrive/UI/View/Files/Preview/OfficePreviewCollectionViewCell.swift
- kDrive/UI/View/Files/Preview/OfficePreviewCollectionViewCell.xib
- kDrive/UI/View/Files/Preview/PdfPreviewCollectionViewCell.swift
- kDrive/UI/View/Files/Preview/PreviewCollectionViewCell.swift
Waiting for answer regarding security here: https://developer.apple.com/forums/thread/693890
> Fix preview + Fix page change xlsx

- kDriveCore/Data/UploadQueue/PhotoLibraryUploader.swift
> Fix threading

- kDrive/AppDelegate.swift
- kDriveFileProvider/FileProviderExtension.swift
> Fix conflict option for FP and Open With

- kDriveCore/Data/Models/UploadFile.swift
- kDriveCore/Data/UploadQueue/PhotoLibraryUploader.swift
- kDriveCore/Utils/PhotoLibrarySaver.swift
> Do not sync downloaded photos

- kDrive/UI/Controller/Files/Categories/ManageCategoriesViewController.swift
- kDrive/UI/Controller/Files/FileListViewController.swift
- kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Home/HomeViewController.swift
- kDrive/UI/View/Files/Categories/CategoryBadgeCollectionViewCell.swift
- kDrive/UI/View/Files/Categories/CategoryBadgeCollectionViewCell.xib
- kDrive/UI/View/Files/FileCollectionViewCell.swift
- kDrive/UI/View/Files/FileCollectionViewCell.xib
- kDrive/UI/View/Files/FileDetail/FileDetailActivityTableViewCell.swift
- kDrive/UI/View/Files/FileGridCollectionViewCell.swift
- kDrive/UI/View/Home/FileHomeCollectionViewCell.swift
- kDriveCore/Data/Models/File.swift
- kDriveCore/Data/Models/FileActivity.swift
- kDriveCore/Data/Models/FileCategory.swift
> Add category badges in file list

- kDrive/UI/View/Files/Preview/OfficePreviewCollectionViewCell.swift
- kDriveCore/Utils/FileImportHelper.swift
> Improve file preview encoding

- kDrive/UI/Controller/Files/FileListViewController.swift
- kDrive/UI/Controller/Menu/SharedWithMe/SharedWithMeViewController.swift
> Fix drag drop

- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/View/Files/FileCollectionViewCell.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/Models/Drive.swift
- kDriveCore/Data/Models/FileCategory.swift
> Sort file categories according to addedToFileAt

- kDrive/UI/Controller/Home/HomeViewController.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
> Delete file cascade

- kDriveCore/Data/UploadQueue/PhotoLibraryUploader.swift
Improve PHAsset fetching also fix #347
> Improve PHAsset fetching

- kDrive/UI/Controller/Files/Search/SearchViewController.swift
- kDrive/UI/View/Files/FileCollectionViewCell.swift
- kDrive/UI/View/Files/Search/RecentSearchCollectionViewCell.swift
- kDrive/UI/View/Files/Search/RecentSearchCollectionViewCell.xib
> Remove recent search + Refactor recent search cell

- kDrive/UI/View/Files/FileCollectionViewCell.swift
> Fix logo image background color when reusing (Fix #476)

- kDrive/UI/Controller/Files/Save File/SelectDriveViewController.swift
- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
- kDriveCore/Data/Cache/AccountManager.swift
> Show selected account in SelectDriveViewController

- kDrive/UI/Controller/Files/MultipleSelectionViewController.swift
> Fix multiselection when leaving view

- kDrive/UI/Controller/Files/FileListViewController.swift
> Prevent drag/drop directory over itself

- kDrive/UI/Controller/Files/Categories/ManageCategoriesViewController.swift
- kDrive/UI/Controller/Files/Files.storyboard
- kDrive/UI/View/Files/Categories/CategoryBadgeCollectionViewCell.swift
- kDrive/UI/View/Files/Categories/CategoryTableViewCell.swift
- kDrive/UI/View/Files/Categories/ColorSelectionCollectionViewCell.swift
- kDrive/UI/View/Files/FileCollectionViewCell.swift
> Improve accessibility

- kDrive/UI/Controller/Create File/PlusButtonFloatingPanelViewController.swift
- kDrive/UI/Controller/FloatingPanelSelectOptionViewController.swift
- kDrive/UI/Controller/MainTabViewController.swift
> Fix plus button and select floating panels height

- .package.resolved
- Project.swift
- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/View/Files/Preview/CodePreviewCollectionViewCell.swift
- kDrive/UI/View/Files/Preview/CodePreviewCollectionViewCell.xib
- kDriveCore/Data/Models/File.swift
> Code preview

- kDriveCore/Utils/Logging.swift
> Re-enable Sentry

- kDrive/UI/Controller/Files/FileDetailViewController.swift
> Prevent header slide in comments

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/View/Files/Categories/ManageCategoriesTableViewCell.swift
- kDrive/UI/View/Files/Categories/ManageCategoriesTableViewCell.xib
- kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkTableViewCell.swift
> Fix categories file disabled

- kDrive/UI/Controller/Files/Categories/ManageCategoriesViewController.swift
> Hide "Add category" button when user is not allowed to create any

- kDrive/UI/Controller/Files/Save File/SelectFolderViewController.swift
> Fix start fake root in select folder view

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/Controller/Home/HomeViewController.swift
- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
- kDrive/UI/Controller/Menu/SwitchUserViewController.swift
- kDrive/UI/Controller/MigrationViewController.swift
- kDrive/UI/Controller/OnboardingViewController.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Cache/AccountManager.swift
- kDriveCore/Data/Cache/DriveInfosManager.swift
- kDriveCore/Data/UploadQueue/PhotoLibraryUploader.swift
- kDriveCore/Data/UploadQueue/UploadOperation.swift
- kDriveCore/Migration/MigrationHelper.swift
- kDriveCore/Utils/PhotoLibrarySaver.swift
Close #438 
Migrating `AccountManager`, `MigrationHelper`, `PhotoLibraryUploader` and `PhotoLibrarySaver`
> Migrate to Swift Concurrency

- kDrive/UI/View/Files/FileDetail/FileDetailCommentPopover.swift
> Users can be selected in the comments likes popover

- .package.resolved
> Fix snackbar button

- kDrive/UI/Controller/DriveErrorViewController.swift
- kDrive/UI/Controller/Files/Categories/ManageCategoriesViewController.swift
- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/Controller/Files/FileListViewController.swift
- kDrive/UI/Controller/Files/Files.storyboard
- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareAndRightsViewController.swift
- kDrive/UI/Controller/Files/Save File/SaveFile.storyboard
- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
- kDrive/UI/Controller/Files/Save File/SelectDriveViewController.swift
- kDrive/UI/Controller/Files/Save File/SelectFolderViewController.swift
- kDrive/UI/Controller/Files/Search/Search.storyboard
- kDrive/UI/Controller/Files/Search/SearchFiltersViewController.swift
- kDrive/UI/Controller/Menu/AboutTableViewController.swift
- kDrive/UI/Controller/Menu/Menu.storyboard
- kDrive/UI/Controller/Menu/MenuViewController.swift
- kDrive/UI/Controller/Menu/NotificationsSettingsTableViewController.swift
- kDrive/UI/Controller/Menu/ParameterTableViewController.swift
- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
- kDrive/UI/Controller/Menu/SharedWithMe/SharedDrivesViewController.swift
- kDrive/UI/Controller/NewFolder/NewFolder.storyboard
- kDrive/UI/Controller/NewFolder/NewFolderTypeTableViewController.swift
- kDrive/UI/Controller/NewFolder/NewFolderViewController.swift
- kDrive/Utils/UINavigationItem+Extension.swift
> Fix back button

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/FileListViewController.swift
- kDrive/UI/Controller/Files/MultipleSelectionViewController.swift
- kDrive/UI/Controller/Files/SelectFloatingPanelTableViewController.swift
- kDriveCore/Data/Api/ApiRoutes.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Api/Endpoint.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/DownloadQueue/DownloadArchiveOperation.swift
- kDriveCore/Data/Models/DownloadArchiveResponse.swift
- kDriveTests/DriveApiTests.swift
- kDriveTests/DriveFileManagerTests.swift
> Use API v2 for undo & archive

- kDrive/UI/View/Files/Preview/AudioCollectionViewCell.swift
- kDrive/UI/View/Files/Preview/VideoCollectionViewCell.swift
- kDriveCore/Data/Api/ApiRoutes.swift
- kDriveCore/Data/Api/Endpoint.swift
- kDriveCore/Data/Cache/PdfPreviewCache.swift
- kDriveCore/Data/DownloadQueue/DownloadOperation.swift
> Use API v2 for downloads

- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDriveCore/Data/Api/ApiRoutes.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Api/Endpoint.swift
- kDriveCore/UI/Alert/AlertFieldViewController.swift
- kDriveCore/UI/Alert/AlertTextViewController.swift
- kDriveCore/UI/Alert/AlertViewController.swift
- kDriveTests/DriveApiTests.swift
> Use API v2 for comments

- kDrive/UI/Controller/Files/Categories/EditCategoryViewController.swift
- kDrive/UI/Controller/Files/Categories/ManageCategoriesViewController.swift
- kDrive/UI/Controller/Files/Categories/ManageCategoryFloatingPanelViewController.swift
- kDriveCore/Data/Api/ApiRoutes.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Api/Endpoint.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveTests/DriveApiTests.swift
- kDriveTests/DriveFileManagerTests.swift
> Use API v2 for categories

- kDrive/UI/Controller/Files/DropBox/ManageDropBoxViewController.swift
- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/NewFolder/NewFolderViewController.swift
- kDriveCore/Data/Api/ApiRoutes.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Api/Endpoint.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/Models/DropBox.swift
- kDriveTests/DriveApiTests.swift
- kDriveTests/DriveFileManagerTests.swift
> Use API v2 for dropboxes

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/FileListViewController.swift
- kDrive/UI/Controller/Files/MultipleSelectionViewController.swift
- kDrive/UI/Controller/Files/SelectFloatingPanelTableViewController.swift
- kDrive/UI/Controller/Menu/Trash/TrashViewController.swift
- kDriveCore/Data/Api/ApiRoutes.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/Models/ApiResponse.swift
- kDriveCore/UI/UIConstants.swift
- kDriveFileProvider/FileProviderExtension+Actions.swift
- kDriveTests/DriveApiTests.swift
- kDriveTests/DriveFileManagerTests.swift
> Use API v2 for file actions

- kDrive/UI/View/Menu/MenuTopTableViewCell.swift
> Hide switch drive icon in menu when user has only one drive

- kDriveCore/Data/DownloadQueue/BackgroundDownloadSessionManager.swift
- kDriveCore/Data/UploadQueue/BackgroundUploadSessionManager.swift
> Fix CRITICAL BUGS 🎉

- kDrive/UI/Controller/Files/FileDetailViewController.swift
> Deleting comment doesn't delete answers

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/View/Files/Preview/NoPreviewCollectionViewCell.swift
- kDrive/UI/View/Files/Preview/NoPreviewCollectionViewCell.xib
- kDriveCore/Utils/FileActionsHelper.swift
> "Open with" button in file preview

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/FilePresenter.swift
- kDrive/UI/View/Files/Preview/NoPreviewCollectionViewCell.swift
- kDrive/UI/View/Files/Preview/NoPreviewCollectionViewCell.xib
- kDriveCore/Data/Models/File.swift
- Display the right file icon and tint
- Show the "Open With" button only if the file is downloaded
- Hide the UIView instead of the UIStackView to have the same margin between button and top element
> Fix "No Preview" cell

- kDrive/UI/Controller/Files/Upload/UploadQueueFoldersViewController.swift
- kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
Hide back button in UploadQueueFolders and UploadQueue views
> Hide back button in Upload Queue views

- kDrive/UI/Controller/Files/SelectFloatingPanelTableViewController.swift
> Bugs when passing files offline in multi-selection

- kDriveCore/Data/Cache/AccountManager.swift
Add actor for account manager to fix a race condition
> Fix race condition in Account Manager

- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
> Inconsistent capitalisation of letters

- kDrive/UI/Controller/Home/HomeOfflineFilesController.swift
- kDrive/UI/Controller/Home/HomeRecentActivitiesController.swift
- kDrive/UI/Controller/Home/HomeRecentFilesController.swift
- kDrive/UI/View/Home/FileHomeCollectionViewCell.xib
> Fix refresh for offline files in home

- kDrive/UI/Controller/Files/FileListViewController.swift
> Bug with multiple selection and landscape

- kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
- kDriveCore/Data/Models/UploadFile.swift
> Fix observation remove old corner handling

- kDrive/UI/Controller/Files/OnlyOfficeViewController.swift
> Fix download/print in OnlyOffice web view

- kDriveCore/Data/Cache/DriveFileManager.swift
> Fix apply activities when deleting dropbox

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
- kDriveCore/Utils/Constants.swift
> Reload file list if activities too old

- kDrive/UI/Controller/Files/File List/MultipleSelectionFileListViewModel.swift
https://user-images.githubusercontent.com/25110022/156370986-3e59a418-c938-42df-8433-941f6b970658.mp4
> Cells remain selected after the cancellation of the multi select

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/File List/MultipleSelectionFileListViewModel.swift
- kDrive/UI/Controller/Files/SelectFloatingPanelTableViewController.swift
- kDriveCore/Data/MQService/BulkAction.swift
Closes #618 
Linked kDrive issue : https://gitlab.infomaniak.ch/infomaniak/team-kdrive/kdrive/-/issues/366
API v2 doc : https://developer.preprod.dev.infomaniak.ch/docs/api/post/2/drive/%7Bdrive_id%7D/files/bulk
> On "all select" can deselect some files

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
> File information panel doesn't close when clicking outside

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/SelectFloatingPanelTableViewController.swift
- kDrive/Utils/MatomoUtils.swift
> Matomo : Update category names according to Android

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/Create File/FloatingPanelUtils.swift
- kDrive/UI/Controller/Create File/PlusButtonFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/Controller/Files/FilePresenter.swift
- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/Controller/FloatingPanelSelectOptionViewController.swift
- kDrive/UI/Controller/Home/HomeViewController.swift
- kDrive/UI/Controller/MainTabViewController.swift
> Refactor tablefloatingpanel

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/Controller/Files/FilePresenter.swift
> Show parent in file list

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
> Remove 10 files limit for MakeOffline

- kDrive/UI/Controller/Files/FilePresenter.swift
> Fix shared with me show parent crash

- kDrive/UI/Controller/Files/Rights and Share/ShareLinkSettingsViewController.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/Models/ShareLink.swift
- kDriveTests/DriveApiTests.swift
> Fix share link settings for free drives

- .package.resolved
> Update Infomaniak Core dependency to fix color

- kDrive/UI/Controller/Alert/AlertDocViewController.swift
- kDrive/UI/Controller/Files/Categories/EditCategoryViewController.swift
- kDrive/UI/Controller/Files/Categories/ManageCategoriesViewController.swift
- kDrive/UI/Controller/Files/DropBox/ManageDropBoxViewController.swift
- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
- kDrive/UI/Controller/Files/File List/MultipleSelectionFileListViewModel.swift
- kDrive/UI/Controller/Files/File List/UnmanagedFileListViewModel.swift
- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/Controller/Files/FilePresenter.swift
- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/OnlyOfficeViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/InviteUserViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareAndRightsViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareLinkSettingsViewController.swift
- kDrive/UI/Controller/Menu/Trash/TrashListViewModel.swift
- kDrive/UI/Controller/NewFolder/NewFolderViewController.swift
- kDrive/Utils/FileActionsHelper.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Api/Endpoint.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/Models/ArchiveBody.swift
- kDriveCore/Data/Models/File.swift
- kDriveCore/UI/UIConstants.swift
- kDriveFileProvider/FileProviderEnumerator.swift
- kDriveFileProvider/FileProviderExtension+Actions.swift
- kDriveTests/DriveApiTests.swift
- kDriveTests/DriveFileManagerTests.swift
Use ProxyFile struct in async context
Resolve ProxyFile to File if needed
Resolves #691
> Thread safety - Very safe PR™

- Project.swift
- kDrive/AppDelegate.swift
- kDrive/Resources/kDrive.entitlements
- kDrive/Utils/UniversalLinksHelper.swift
> Add universal/deep link support

- kDriveCore/Data/UploadQueue/PhotoLibraryUploader.swift
> Fix PHAsset upload file extension

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
Linked to Android: https://github.com/Infomaniak/android-kDrive/pull/719
> Update actions order to be the same everywhere (FileInfo, MultiSelect, Android, iOS)

- kDrive/Utils/FileActionsHelper.swift
- kDriveCore/Utils/PhotoLibrarySaver.swift
> Refactor PhotoLibrarySaver & fix saving image

- kDrive/UI/Controller/Favorite/FavoritesViewModel.swift
- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
- kDrive/UI/Controller/Files/File List/InMemoryFileListViewModel.swift
- kDrive/UI/Controller/Files/File List/UnmanagedFileListViewModel.swift
- kDrive/UI/Controller/Files/RecentActivityFilesViewController.swift
- kDrive/UI/Controller/Files/Search/SearchViewController.swift
- kDrive/UI/Controller/Menu/LastModificationsViewModel.swift
- kDrive/UI/Controller/Menu/MySharesViewModel.swift
- kDrive/UI/Controller/Menu/OfflineFilesViewModel.swift
- kDrive/UI/Controller/Menu/PhotoList/PhotoListViewController.swift
- kDrive/UI/Controller/Menu/PhotoList/PhotoListViewModel.swift
- kDrive/UI/Controller/Menu/Trash/TrashListViewModel.swift
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveTests/DriveApiTests.swift
- kDriveTests/DriveFileManagerTests.swift
Use in memory realm for 
- TrashList
- SearchList
- RecentActivitiesList
Closes #688
> In memory realm

- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
- kDrive/UI/Controller/Menu/Trash/TrashListViewModel.swift
- kDrive/Utils/MatomoUtils.swift
> Matomo : track cell swipe actions

- kDrive/UI/Controller/Home/HomeViewController.swift
Home reloading wasn't happening serially which could lead to issues and crash while enumerating the viewmodel. 
Calls are now done using a serial queue to prevent concurrent modifications.
Fix #743
> Use serial queue for home reloading

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/View/Files/Preview/VideoCollectionViewCell.swift
> Fix video dismiss

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDriveCore/Data/UploadQueue/BackgroundUploadSessionManager.swift
- Log didBecomeInvalidWithError to see if could the root cause of upload issues.
> Log invalid sessions + Refresh header / emptyview only if needed

- kDriveCore/Utils/FileImportHelper.swift
> Compress PDF scan file

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/Search/SearchViewController.swift
- kDrive/UI/Controller/Menu/Menu.storyboard
- kDrive/UI/Controller/Menu/PhotoList/PhotoListViewController.swift
> Fix search filters reload

- kDrive/UI/Controller/Menu/PhotoList/PhotoListViewController.swift
> Add header inset for scroll indicator

- kDrive/UI/View/Files/FileCollectionViewCell.swift
> Fix offline checkmark

- kDriveActionExtension/ActionNavigationController.swift
- kDriveShareExtension/ShareNavigationViewController.swift
> Fix share sheet size iPad

- kDrive/UI/View/Files/FileDetail/ShareLink/InviteUserTableViewCell.xib
> Change keyboard type in share text field

- kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
Attempt at fixing crash when reloading cell corners in uploadqueue viewcontroller
> Reload outside completion

- kDrive/UI/Controller/Files/DropBox/ManageDropBoxViewController.swift
- kDrive/UI/Controller/NewFolder/NewFolderViewController.swift
- kDrive/UI/View/NewFolder/NewFolderSettingsTableViewCell.swift
- kDriveCore/Data/Models/DropBox.swift
> Fix dropbox size decimal

- kDrive/UI/Controller/Files/FileDetailViewController.swift
> Fix & improve file detail activity sections

- kDrive/Resources/en.lproj/Localizable.stringsdict
- kDrive/Resources/fr.lproj/Localizable.stringsdict
- kDrive/Resources/it.lproj/Localizable.stringsdict
Some snackbar confirmation messages were in the wrong language.
Fix #817
> Fix Localizable.stringsdict

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/RecentActivityFilesViewController.swift
- Fix crash home object already in realm
> Copy to realm only if needed

- kDrive/UI/Controller/MainTabViewController.swift
Fix for #KDRIVE-IOS-1XH #KDRIVE-IOS-1WQ
> Prevent nil driveFileManager

- kDrive/UI/View/Files/FileCollectionViewCell.xib
- kDrive/UI/View/Files/FileGridCollectionViewCell.xib
> Increase "More" button hitbox size (FileList cells)

- kDrive/UI/Controller/Files/Save File/SelectFolderViewController.swift
- kDrive/UI/View/EmptyTableView/EmptyTableView.swift
> Move folder: use noFilesDescriptionSelectFolder

- kDrive/Utils/MatomoUtils.swift
> Update Matomo for the new link sharing event

- kDrive/UI/View/Files/FloatingPanel/FloatingPanelActionCollectionViewCell.swift
> Download progress from multiselect doesn't disappear

- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
> Do not allow archive download if files have not the same parent

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
- kDrive/Utils/FileActionsHelper.swift
> Present DocumentPicker even if FileActionsPanel is dismissed

- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
> Prevent crash when current directory has been deleted elsewhere

- kDrive/Resources/de.lproj/Localizable.strings
- kDrive/Resources/en.lproj/Localizable.strings
- kDrive/Resources/es.lproj/Localizable.strings
- kDrive/Resources/fr.lproj/Localizable.strings
- kDrive/Resources/it.lproj/Localizable.strings
- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
- kDrive/Utils/FileActionsHelper.swift
- kDriveCore/Data/Models/DriveError.swift
- kDriveCore/Utils/PhotoLibrarySaver.swift
> Create better error when photo library access is limited

- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
> Fix PhotoSyncSettingsViewController crash when updating tableView

- kDrive/UI/View/Files/SaveFile/FileNameTableViewCell.swift
- kDriveCore/UI/Alert/AlertFieldViewController.swift
- kDriveCore/UI/MaterialOutlinedTextField+Extension.swift
- kDriveCore/Utils/TextFieldConfiguration.swift
> Add clean button for TextField (SaveFileViewController)

- .package.resolved
Upgrade Infomaniak core to fix a bug with user profile fetching
Upgrade Realm
> Upgrade dependencies

- kDrive/UI/View/Files/FileCollectionViewCell.swift
> Cancel task only when reusing

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/Alert/AlertDocViewController.swift
- kDrive/UI/Controller/Files/Categories/EditCategoryViewController.swift
- kDrive/UI/Controller/Files/Categories/ManageCategoriesViewController.swift
- kDrive/UI/Controller/Files/Categories/ManageCategoryFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/ColorSelectionFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/DropBox/ManageDropBoxViewController.swift
- kDrive/UI/Controller/Files/File List/DragAndDropFileListViewModel.swift
- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
- kDrive/UI/Controller/Files/File List/MultipleSelectionFileListViewModel.swift
- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/Controller/Files/FilePresenter.swift
- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/OnlyOfficeViewController.swift
- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareAndRightsViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareLinkSettingsViewController.swift
- kDrive/UI/Controller/Home/HomeRecentFilesController.swift
- kDrive/UI/Controller/MainTabViewController.swift
- kDrive/UI/Controller/Menu/SharedWithMe/SharedDrivesViewController.swift
- kDrive/UI/Controller/Menu/Trash/TrashListViewModel.swift
- kDrive/UI/Controller/NewFolder/NewFolderViewController.swift
- kDrive/UI/Controller/Photo/PhotoPickerDelegate.swift
- kDrive/Utils/FileActionsHelper.swift
- kDrive/Utils/UniversalLinksHelper.swift
- kDriveCore/Data/Models/DriveError.swift
- kDriveCore/UI/UIConstants.swift
Only use one entry point to display errors. Close #874
> Error refactor

- kDriveCore/Data/UploadQueue/BackgroundUploadSessionManager.swift
Previously no access control was done on `BackgroundSessionManager` properties but this class is heavily multithreaded and this can lead to race conditions. Potential fix for KDRIVE-IOS-1Z4
> Add lock queue to prevent race conditions

- kDrive/UI/Controller/Menu/PhotoList/PhotoListViewModel.swift
> PhotoList sort mode

- kDrive/UI/Controller/Files/OnlyOfficeViewController.swift
> OnlyOffice black screen

- kDrive/AppDelegate.swift
- kDrive/UI/Controller/Base.lproj/Main.storyboard
- kDrive/UI/Controller/DriveErrorViewController.swift
- kDrive/UI/Controller/Floating Panel Information/DriveMaintenanceFloatingPanelViewController.swift
- kDrive/UI/Controller/Home/SelectSwitchDriveDelegate.swift
- kDrive/UI/Controller/Menu/SharedWithMe/SharedDrivesViewController.swift
- kDrive/UI/Controller/Menu/SwitchUserViewController.swift
- kDrive/UI/Controller/OnboardingViewController.swift
- kDriveCore/Data/Cache/AccountManager.swift
- kDriveCore/Data/Cache/DriveInfosManager.swift
- kDriveCore/Data/Models/Drive.swift
- kDriveCore/Data/Models/DriveError.swift
- kDriveCore/Utils/Constants.swift
> Handle maintenance

- kDrive/Resources/de.lproj/Localizable.strings
- kDrive/Resources/en.lproj/Localizable.strings
- kDrive/Resources/es.lproj/Localizable.strings
- kDrive/Resources/fr.lproj/Localizable.strings
- kDrive/Resources/it.lproj/Localizable.strings
- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
> Remove "allDuplicateFileName"

- kDrive/UI/Controller/NewFolder/NewFolderViewController.swift
- kDriveCore/Data/UploadQueue/UploadQueue.swift
- kDriveCore/UI/Alert/AlertFieldViewController.swift
> Trim file/folder names

- kDrive/UI/View/Files/FileCollectionViewCell.swift
> Folder color not updated

- kDrive/UI/Controller/Files/Categories/ManageCategoriesViewController.swift
- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
- kDrive/Utils/FileActionsHelper.swift
> Edit categories in multiple selection

- kDrive/UI/Controller/Create File/PlusButtonFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
- kDrive/UI/Controller/MainTabViewController.swift
- kDrive/UI/Controller/Scan/SaveScanViewController.swift
- kDrive/UI/Controller/Scan/ScanNavigationViewController.swift
- kDriveCore/Utils/DriveUserDefaults+Extension.swift
> Save last selected folder for a scan

- .package.resolved
- Project.swift
- kDriveCore/Data/Cache/AccountManager.swift
Depends on [ios-login#3](https://github.com/Infomaniak/ios-login/pull/3)
Closes #862
> Delete API token when user is disconnected

- kDrive/UI/Controller/Menu/Trash/TrashListViewModel.swift
> [TrashList] Multiple selection: Realm accessed from incorrect thread

- kDrive/UI/Controller/Create File/DriveImportDocumentPickerViewController.swift
- kDrive/UI/Controller/Create File/PlusButtonFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/Save File/SelectDriveViewController.swift
- kDrive/UI/Controller/MainTabViewController.swift
- kDrive/UI/Controller/Menu/SharedWithMe/SharedDrivesViewController.swift
- kDriveCore/Data/Cache/DriveInfosManager.swift
> Shared With Me: show tabBar and allow upload

- kDrive/UI/View/Files/FileDetail/ShareLink/UsersAccessTableViewCell.swift
- kDriveCore/Data/Models/DriveUser.swift
- kDriveCore/Data/Models/FileAccess.swift
Closes #854.
Linked to android: [#816](https://github.com/Infomaniak/android-kDrive/pull/816)
> Remove deprecated `type` in DriveUser et UserFileAccess

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/View/Files/FileCollectionViewCell.swift
- kDrive/UI/View/Files/FileCollectionViewCell.xib
- kDrive/UI/View/Files/FileDetail/FileDetailActivityTableViewCell.swift
- kDrive/UI/View/Files/FileGridCollectionViewCell.swift
- kDrive/UI/View/Files/FileGridCollectionViewCell.xib
- kDriveCore/Data/Api/DriveApiFetcher.swift
- kDriveCore/Data/Api/Endpoint.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/MQService/ActionNotification.swift
- kDriveCore/Data/MQService/ActionType.swift
- kDriveCore/Data/MQService/MQService.swift
- kDriveCore/Data/Models/DriveError.swift
- kDriveCore/Data/Models/File.swift
- kDriveCore/Data/Models/FileActivity.swift
> Display external import folders

- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
- kDrive/UI/Controller/Scan/SaveScanViewController.swift
> SaveFileVC from app should not let user select drive

- kDriveCore/Data/DownloadQueue/DownloadQueue.swift
- kDriveCore/Data/UploadQueue/UploadQueue.swift
- kDriveCore/Utils/OperationQueueHelper.swift
> Keep screen on when Upload/Download is in progress

- kDrive/UI/View/Files/FileCollectionViewCell.swift
- kDrive/UI/View/Files/FileGridCollectionViewCell.swift
> Show thumbnail in multiselection

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareLinkSettingsViewController.swift
- kDrive/UI/Controller/Menu/MenuViewController.swift
- kDrive/UI/Controller/Menu/StoreViewController.swift
- kDrive/UI/Controller/NewFolder/NewFolderTypeTableViewController.swift
- kDrive/UI/View/Menu/Store/StoreCollectionViewCell.swift
- kDrive/Utils/FileActionsHelper.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/Cache/DriveInfosManager.swift
- kDriveCore/Data/Models/Drive.swift
> Add new drive pack

- kDrive/UI/Controller/Files/OnlyOfficeViewController.swift
- kDrive/UI/View/Files/Preview/OfficePreviewCollectionViewCell.swift
> Office files: open links in Safari

- kDrive/Resources/de.lproj/Localizable.strings
- kDrive/Resources/en.lproj/Localizable.strings
- kDrive/Resources/es.lproj/Localizable.strings
- kDrive/Resources/fr.lproj/Localizable.strings
- kDrive/Resources/it.lproj/Localizable.strings
- kDrive/UI/Controller/Create File/PlusButtonFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
- kDrive/UI/Controller/Photo/PhotoPickerDelegate.swift
- kDrive/UI/View/Menu/Parameters/ParameterAccessDeniedTableViewCell.swift
- kDrive/UI/View/Menu/PhotoSyncSettings/PhotoAccessDeniedTableViewCell.swift
- kDriveCore/Data/UploadQueue/PhotoLibraryUploader.swift
- kDriveCore/Utils/Constants.swift
- kDriveCore/Utils/FileImportHelper.swift
- kDriveCore/Utils/PHAsset+Exension.swift
- kDriveCore/Utils/PhotoLibrarySaver.swift
> Disable video reencoding

- kDrive/UI/Controller/Menu/AppLockSettingsViewController.swift
> Fix LockScreen not presented correctly

- kDrive/UI/View/Files/FileCollectionViewCell.swift
- kDrive/UI/View/Files/FileGridCollectionViewCell.swift
`FileHomeCollectionViewCell` doesn't have an `externalImportProgress`
> FileCollectionViewCell: fix importProgressView

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/MainTabViewController.swift
- kDrive/UI/Controller/Menu/MenuViewController.swift
- kDrive/UI/Controller/Menu/SharedWithMe/SharedDrivesViewController.swift
- kDrive/UI/View/Menu/MainTabBar.swift
> MainTabBar: fix Plus Button state bug

- kDrive/UI/Controller/Files/FileDetailViewController.swift
- kDrive/UI/View/Files/Categories/ManageCategoriesTableViewCell.swift
- kDrive/UI/View/Files/Categories/ManageCategoriesTableViewCell.xib
- ~~We should not fetch data if the file is disabled~~ (will be discussed later)
> FileDetailsViewController: update view

- kDrive/Resources/de.lproj/Localizable.strings
- kDrive/Resources/en.lproj/Localizable.strings
- kDrive/Resources/es.lproj/Localizable.strings
- kDrive/Resources/fr.lproj/Localizable.strings
- kDrive/Resources/it.lproj/Localizable.strings
- kDriveCore/Data/Models/Category.swift
Add category "PREDEF_CAT_RESUME"
> Add new category "resume"

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
> FileListView: fix layout issue on rotation

- kDrive/UI/Controller/Files/Categories/EditCategoryViewController.swift
- kDrive/UI/Controller/Files/Categories/ManageCategoriesViewController.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
> Fix categories

- kDrive/Resources/de.lproj/Localizable.strings
- kDrive/Resources/en.lproj/Localizable.strings
- kDrive/Resources/es.lproj/Localizable.strings
- kDrive/Resources/fr.lproj/Localizable.strings
- kDrive/Resources/it.lproj/Localizable.strings
- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/Save File/SelectFolderViewController.swift
- kDrive/UI/Controller/Menu/MenuViewController.swift
- kDrive/UI/View/EmptyTableView/EmptyTableView.swift
> "Click on (+) button": do not display if user doesn't have rights and display tab bar in My Shares #952

- kDrive/UI/Controller/Menu/LastModificationsViewModel.swift
> Fix Most Recent Changes order

- kDrive/UI/Controller/Files/ColorSelectionFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
- kDrive/UI/View/Files/FloatingPanel/FloatingPanelActionCollectionViewCell.swift
> Coloring a folder in multiselection with a disabled folder is not applied until refresh

- kDriveCore/Data/Models/UploadFile.swift
- kDriveCore/Utils/FileImportHelper.swift
- kDriveCore/Utils/PHAsset+Exension.swift
Keep creation and modification date
> Fix JPEG data

- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/DownloadQueue/DownloadOperation.swift
- kDriveCore/Data/Models/File.swift
Excluding part of the app content from system backup.
Are Excluded :
- Main Realm DB
- Upload Realm DB
- Custom cache download path
- Every downloaded file
> Exclude cached content from System backup

- kDriveCore/Data/UploadQueue/Servicies/PhotoLibraryUploader.swift
Fix a realm related crash on photo roll cleanup.
Using Primary Keys to do the job, tested on my side, scale up well.
> fix crash on photo removal

- .package.resolved
- Project.swift
- kDrive/UI/Controller/Files/Categories/ManageCategoryFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/ColorSelectionFloatingPanelViewController.swift
- kDrive/UI/Controller/Home/HomeViewController.swift
- kDrive/UI/Controller/Menu/MenuViewController.swift
- kDrive/UI/Controller/Menu/StoreViewController.swift
- kDrive/Utils/UploadCountManager.swift
- kDriveCore/Utils/Throttler.swift
Resolved multiple UI glitches regarding keeping the uploading count updated
- Upload count in HomeView controller fails to live update.
- When hidden, Upload Count does not update in MenuViewController, which is an issue when it reaches 0 and does not dissapear.
Bump Core-UI
https://github.com/Infomaniak/ios-core-ui/pull/7
> fix(UploadCountObservation): Resolved multiple UI glitches

- kDrive/Utils/FileActionsHelper.swift
- kDriveCore/DI/FactoryService.swift
- kDriveCore/Data/DownloadQueue/DownloadOperation.swift
- kDriveCore/Data/DownloadQueue/DownloadQueue.swift
- kDriveCore/Data/Models/File.swift
- kDriveCore/Data/UploadQueue/Servicies/PhotoLibraryUploader.swift
- kDriveCore/Utils/PhotoLibrarySaver.swift
- fix(File.isDownloaded): Now able to start back download after a first download that did not finish completely
- refactor: Misc related changes
> Fix download video does not restart

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
- kDrive/UI/View/Files/Upload/UploadTableViewCell.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+Database.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+Error.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation.swift
- kDriveCore/Data/UploadQueue/Queue/UploadQueue+Observation.swift
- kDriveCore/Data/UploadQueue/Queue/UploadQueue+Publish.swift
- kDriveCore/Data/UploadQueue/Queue/UploadQueue+Queue.swift
- kDriveCore/Utils/NotificationsHelper.swift
- kDriveCore/Utils/SentryDebug.swift
- more specific sentry code where needed
- refactor sentry code for readability
- fix UI not reflecting the upload state right away.
- Track photo versions in base in order to upload only edited files when needed.
- try to fix NSInternalInconsistencyException (last crash with volumetry on Sentry)
> More sentry for next beta

- Tuist/ProjectDescriptionHelpers/Constants.swift
- kDriveCore/Data/Api/DriveApiFetcher+Upload.swift
- kDriveCore/Data/Api/Endpoint.swift
- kDriveCore/Data/Models/DriveError.swift
- kDriveCore/Data/Models/Upload/UploadFile.swift
- kDriveCore/Data/Models/Upload/UploadingChunkTask.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+Database.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+Datasource.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+Error.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation.swift
- kDriveCore/Utils/Logging.swift
- kDriveCore/Utils/SentryDebug.swift
- Suport for suspension with chunks
- Sync session state with server 
- Retry on specific chunk in error
- More detailed Sentry errors
> feat: Changes related to 4.3.4-10

- Tuist/ProjectDescriptionHelpers/Constants.swift
- kDrive/AppDelegate.swift
- kDrive/UI/Controller/Files/Categories/EditCategoryViewController.swift
- kDrive/UI/Controller/Files/DropBox/ManageDropBoxViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/InviteUserViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareLinkSettingsViewController.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
- kDrive/UI/Controller/NewFolder/NewFolderViewController.swift
- kDrive/UI/Controller/Photo/SavePhotoViewController.swift
- kDrive/UI/Controller/Scan/SaveScanViewController.swift
- kDrive/UI/View/Footer view/FooterButtonView.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation.swift
fix: Remove extraneous error displayed to the user.
fix: Notifications cleaned on app going to foreground.
fix: Cannot break SaveViewController by spamming the save button
> feat: Changes related to 4.3.4-12

- kDriveCore/Data/Api/DriveApiFetcher.swift
quickwin, reuse code to bump `UserAgent` format like `Mail`
> feat: Change kDrive user agent like it was done to Mail

- kDrive/UI/Controller/Menu/PhotoList/PhotoListViewController.swift
- kDrive/UI/View/Files/FileCollectionViewCell.swift
- kDriveCore/Data/Models/File.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+Database.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+Error.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+ExpiringActivityDelegate.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+UploadChunk.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation.swift
- kDriveCore/Data/UploadQueue/Queue/UploadQueue.swift
Fix https://github.com/Infomaniak/ios-kDrive/issues/984
> fix(UploadOperation): Seamless switch between WIFI and Cellular data.

- Tuist/ProjectDescriptionHelpers/Constants.swift
- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
- kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
- kDrive/UI/Controller/Menu/LastModificationsViewModel.swift
- kDrive/UI/Controller/Menu/PhotoList/PhotoListViewModel.swift
- kDrive/UI/Controller/Menu/Trash/TrashListViewModel.swift
- kDrive/UI/View/Files/FileCollectionViewCell.swift
- kDrive/UI/View/Files/FileGridCollectionViewCell.swift
- kDrive/UI/View/Home/FileHomeCollectionViewCell.swift
- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+Database.swift
- kDriveCore/Data/UploadQueue/Operation/UploadOperation+Error.swift
- kDriveCore/Utils/SentryDebug.swift
Abstract: 3 bugfixes, details in commits.
> fix: Changes realted to 4.3.5-3

- kDrive/UI/Controller/RegisterViewController.swift
- kDriveCore/Utils/Constants.swift
Redirect route was changed from drive.infomaniak.com to kdrive.infomaniak.com
> fix: Update drive register route

- kDriveCore/Data/Cache/DriveFileManager.swift
- kDriveCore/Utils/SentryDebug.swift
The handling of Realm migration errors will be done and tested later, this is a stopgap.
- Some refactor for cleaner Realm Migration
- Sentry breadcrumbs on migration entry and exit
> feat: Stopgap migration crash

- .package.resolved
- Project.swift
- kDrive/AppDelegate+Launch.swift
- kDrive/AppDelegate.swift
- kDrive/UI/Controller/MigrationViewController.swift
- kDrive/UI/Controller/OnboardingViewController.swift
- kDriveCore/DI/FactoryService.swift
… like it was done for mail to be able to use the latest Core version.
> feat: Migration to use AppLaunchCounter on kDrive

- .package.resolved
- Project.swift
- kDrive/AppDelegate+Launch.swift
- kDrive/AppDelegate.swift
- kDrive/UI/Controller/MigrationViewController.swift
- kDrive/UI/Controller/OnboardingViewController.swift
> fix: New fixed Core lib

- kDrive/UI/Controller/Scan/SaveScanViewController.swift
- kDriveCore/UI/Scan/SaveScanWorker.swift
- kDriveCore/UI/Scan/SaveScanWorkerDelegate.swift
- kDriveCore/Utils/Files/FileImportHelper+Upload.swift
Fix main thread use in document importation
> fix: Made SaveScanViewController process in the background

- kDrive/UI/Controller/Menu/MenuViewController.swift
- kDriveTests/kDriveCore/MenuViewControllerTests.swift
- fix: Observation not starting
- refactor: Removed use of force unwrap
- test: Testing that observation starts at MenuViewController init.
> fix: Missing upload progress UI in MenuViewController

- kDrive/UI/Controller/LockedAppViewController.swift
- kDriveCore/DI/FactoryService.swift
- kDriveTests/kDrive/Launch/ITAppLaunchTest.swift
- kDriveTests/kDrive/Launch/MockAccountManager.swift
- kDriveTests/kDrive/Launch/UTRootViewControllerState.swift
> test: Test app launch

- kDriveCore/Data/UploadQueue/Queue/UploadParallelismHeuristic.swift
Starting to reduce the system load by some amount at .serious state.
> feat: Start to reduce the system load earlier, at .serious thermal state

- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
> fix: EmptyView not showing

- kDrive/UI/Controller/Scan/SaveScanViewController.swift
- kDrive/UI/Controller/Scan/ScanNavigationViewController.swift
- kDriveCore/Utils/Files/FileImportHelper+Upload.swift
- kDriveCore/Utils/Files/FileImportHelper.swift
Also improved the rendering to use more cores.
> feat: PDF Generation uses a correct page size

- kDrive/UI/Controller/Base.lproj/Main.storyboard
- kDrive/UI/Controller/LockedAppViewController.swift
https://github.com/Infomaniak/ios-kDrive/assets/25110022/f8bd59c9-80f4-4fcd-a447-7126323d8d61
> feat(LockedAppViewController): Unlock button should be loading while evaluating policy

- kDrive/AppDelegate.swift
"navigate" action on a snackbar, after an upload is finished was broken on APIV3 branch.
This fixes that.
> fix: Navigate button fixed for APIV3 view changes

- kDrive/UI/Controller/Base.lproj/Main.storyboard
- kDrive/UI/Controller/Files/Files.storyboard
- kDrive/UI/Controller/Files/Save File/SaveFile.storyboard
- kDrive/UI/Controller/Files/Search/Search.storyboard
- kDrive/UI/Controller/Floating Panel Information/InformationFloatingPanel.storyboard
- kDrive/UI/Controller/Home/Home.storyboard
- kDrive/UI/Controller/Menu/Menu.storyboard
- kDrive/UI/Controller/NewFolder/NewFolder.storyboard
- kDrive/UI/Controller/Photo/Photo.storyboard
- kDrive/UI/Controller/Scan/Scan.storyboard
Storyboard clean-up
Main PR https://github.com/Infomaniak/ios-kDrive/pull/1187
> chore: Removed Storyboard Restoration ID from storyboards

- kDrive/Resources/de.lproj/Localizable.strings
- kDrive/Resources/en.lproj/Localizable.strings
- kDrive/Resources/es.lproj/Localizable.strings
- kDrive/Resources/fr.lproj/Localizable.strings
- kDrive/Resources/it.lproj/Localizable.strings
- kDrive/UI/Controller/Create File/PlusButtonFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
- kDrive/UI/Controller/Files/RootMenuViewController.swift
- kDrive/UI/View/Files/SaveFile/LocationTableViewCell.swift
- kDriveCore/Data/Models/File.swift
- kDriveCore/Data/Models/Upload/UploadFile.swift
- kDriveCore/FileProvider/FileProviderItem.swift
- kDriveCore/FileProvider/FileProviderItemProvider.swift
- kDriveCore/Utils/LocalizedFilenameFormatter.swift
- kDriveFileProvider/Enumerators/DirectoryEnumerator.swift
- kDriveFileProvider/Enumerators/RootEnumerator.swift
- kDriveFileProvider/Enumerators/WorkingSetEnumerator.swift
- kDriveFileProvider/FileProviderExtension+Actions.swift
- kDriveFileProvider/FileProviderExtension.swift
Private space root is named differently based on drivePack
> fix: Correctly name private root

- kDrive/UI/View/Files/Search/SearchFilterCollectionViewCell.xib
> fix(SearchFilterCollectionViewCell): Using a color that works in dark mode

- Tuist/ProjectDescriptionHelpers/Constants.swift
> chore: Bump to 5.0.0

- kDrive/UI/Controller/Home/HomeRecentActivitiesController.swift
- kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
refactor: Removed some legacy GCD code
> fix: Attempt to fix what looks like a realm race condition by doing a refactor

- kDrive/AppRouter.swift
- kDrive/UI/Controller/Floating Panel Information/InformationFloatingPanelViewController.swift
- kDrive/UI/Controller/LaunchPanelsController.swift
- kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
Some leftover XIB loading code was removed, and a crash on table view refresh was fixed also.
> fix(PhotoSyncSettingsViewController): This class no longer uses a storyboard to load

- Tuist/Package.resolved
- Tuist/Package.swift
> chore: Bump libraries, trying to fix a realm crash

- kDrive/UI/Controller/Menu/SecurityTableViewController.swift
- kDriveCore/Data/Cache/DriveInfosManager/DriveInfosManager+FileProvider.swift
- kDriveCore/Data/Cache/DriveInfosManager/DriveInfosManager.swift
Soft disable of Files.App from kDrive should hide all accounts.
> fix(Files.app): Drives are hidden on soft disable from the app

- kDrive/UI/Controller/LaunchPanelsController.swift
In some corner cases, we had a crash during a logout. This is a quick win to prevent a crash.
> fix: Crash while switch account in some conditions

- kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
- kDriveCore/Data/Models/File+URL.swift
Broken since 5.0.0-8 by #1260
The recursion was OK, but the root file was not removed.
> fix(DriveFileManager): Deleting a file was broken

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/UI/View/Files/FloatingPanel/FloatingPanelActionCollectionViewCell.swift
- kDrive/Utils/FileActionsHelper.swift
> feat: Select all offline

- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
- kDrive/UI/Controller/Menu/OfflineFilesViewModel.swift
> fix: Correctly display empty view offline

- kDrive/UI/Controller/Files/File List/FileListViewModel.swift
In some cases empty directory wasn't reported correctly. For example on initial opening of an empty directory.
> fix: Correctly observe parent directory for empty files

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/View/Files/Preview/CodePreviewCollectionViewCell.swift
When displaying a text file the UI was freezing.
> fix(PreviewViewController): Read files outside of the main actor

- kDrive/AppRouter.swift
State restoration in preview now working as espected.
> fix: State restoration in preview

- kDrive/Resources/de.lproj/Localizable.strings
- kDrive/Resources/en.lproj/Localizable.strings
- kDrive/Resources/es.lproj/Localizable.strings
- kDrive/Resources/fr.lproj/Localizable.strings
- kDrive/Resources/it.lproj/Localizable.strings
Bump i18n to the latest version of texts that include "public shares"
> chore: Fetch i18n to date

- kDrive/Resources/de.lproj/Localizable.strings
- kDrive/Resources/en.lproj/Localizable.strings
- kDrive/Resources/es.lproj/Localizable.strings
- kDrive/Resources/fr.lproj/Localizable.strings
- kDrive/Resources/it.lproj/Localizable.strings
Reverts Infomaniak/ios-kDrive#1330
> Revert "chore: Fetch i18n to date"

- Tuist/Package.resolved
- Tuist/ProjectDescriptionHelpers/Constants.swift
Bump to 5.0.2 and update deps where possible.
> chore: Bump 502

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController+Actions.swift
- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
- kDrive/Utils/FileActionsHelper.swift
Free accounts will be presented with an upsale sheet.
> fix: Free accounts can see change color action

- Tuist/Package.resolved
- Tuist/Package.swift
This fixes a parsing bug, therefore classified as a bugfix
> chore: Bump ios-core

- kDrive/UI/View/Files/Preview/AudioCollectionViewCell.xib
IKLabel wasn't imported correctly in XIB and no text style was set.
> fix(AudioCollectionViewCell): Correctly import IKLabel

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDrive/UI/View/Files/Preview/AudioCollectionViewCell.swift
- kDriveCore/AudioPlayer/SingleTrackPlayer.swift
> fix: Handle AVPlayer.currentItem.status error

- kDrive/UI/Controller/LoginDelegateHandler.swift
- kDrive/UI/Controller/OnboardingViewController.swift
Factorised login delegate code in order to help new developments. Public Share needs it.
> refactor(OnboardingViewController): Factorised login delegate

- kDrive/UI/Controller/Menu/Trash/TrashListViewModel.swift
Empty trash logic was not checking the correct source of truth
> fix(TrashListViewModel): Empty trash button logic

- kDriveCore/Data/DownloadQueue/DownloadOperation/DownloadArchiveOperation.swift
- kDriveCore/Data/DownloadQueue/DownloadOperation/DownloadPublicShareArchiveOperation.swift
- kDriveCore/Data/DownloadQueue/DownloadQueue.swift
Root PR : https://github.com/Infomaniak/ios-kDrive/pull/1311
> refactor(DownloadArchiveOperation): Split code related to publicShare

- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
> fix(MultipleSelectionFloatingPanelViewController): Correct background color

- .github/workflows/ci.yml
Quickwin, any open PR will have a CI check.
> feat(CI): Make sure CI runs on any OPEN PR

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController+Actions.swift
- kDrive/UI/Controller/Files/PublicShareAction.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController+FooterButtonDelegate.swift
- kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
- kDrive/UI/Controller/Menu/Share/PublicShareViewModel.swift
- kDrive/UI/View/Upsale/UpsaleViewController.swift
- kDriveCore/Utils/MatomoUtils.swift
This PR hooks new actions to existing events added to feature PR earlier.
> feat: Public share Matomo

- kDrive/UI/Controller/Create File/FloatingPanelLayouts.swift
Made sure it works on iPhone8 iOS16, iPhoneSE iOS 17, iPhone 11 Pro Max iOS 18.
> fix: Public Share action sheet offset

- kDriveCore/VideoPlayer/VideoPlayer.swift
> feat: Public Share video streaming in previews

- kDrive/AppDelegate.swift
> chore(AppDelegate): Clean Public Share sample links

- kDrive/UI/View/Files/FileGridCollectionViewCell.swift
> feat(FileGridCollectionViewCell): Preview thumbnails

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDriveCore/Data/DownloadQueue/DownloadQueue.swift
> feat(PreviewViewController): Download in cache public share files for preview

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
> fix(PreviewViewController): Disable edit button in public share mode

- kDrive/UI/Controller/Files/File List/FileListViewController.swift
- kDriveCore/UI/UIConstants.swift
> fix(FileListViewController): Bottom padding in public share mode

- kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
- kDriveCore/AudioPlayer/SingleTrackPlayer.swift
including [Flac](https://github.com/Infomaniak/ios-kDrive/pull/1336) by having a correct error handling
> fix(publicShare): Audio preview

- kDrive/Resources/de.lproj/Localizable.strings
- kDrive/Resources/en.lproj/Localizable.strings
- kDrive/Resources/es.lproj/Localizable.strings
- kDrive/Resources/fr.lproj/Localizable.strings
- kDrive/Resources/it.lproj/Localizable.strings
Bump all i18n to date.
Can be merged ASAP
Required by MyKSuite quotas https://github.com/Infomaniak/ios-kDrive/pull/1409
> chore(Localizable.strings): Ran script to update all

- kDrive/Resources/de.lproj/Localizable.strings
- kDrive/Resources/en.lproj/Localizable.strings
- kDrive/Resources/es.lproj/Localizable.strings
- kDrive/Resources/fr.lproj/Localizable.strings
- kDrive/Resources/it.lproj/Localizable.strings
Reverts Infomaniak/ios-kDrive#1416 as this should be part of the `myKSuite UI feature` and not the app.
> chore: Revert "chore(Localizable.strings): Ran script to update all"

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController+Actions.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareLinkSettingsViewController.swift
- kDrive/UI/Controller/Home/HomeViewController.swift
- kDrive/UI/Controller/Menu/MenuViewController.swift
- kDrive/UI/Controller/NewFolder/NewFolderTypeTableViewController.swift
- kDrive/Utils/FileActionsHelper.swift
Feature PR https://github.com/Infomaniak/ios-kDrive/pull/1405
Superseding https://github.com/Infomaniak/ios-kDrive/pull/1425/commits
Hiding the upsale banner in settings
Swapping open store router call for the new modal.
> feat: Rework existing limitations

- .github/workflows/dependent-issues.yml
So I can build dependent PRs like with other repositories we have.
> feat: Dependent issues GH workflow

- ci_scripts/ci_post_xcodebuild.sh
Apple doc for ref for $CI_DERIVED_DATA_PATH
https://developer.apple.com/documentation/xcode/environment-variable-reference
> ci: Use correct path + include sources

- kDrive/UI/Controller/Menu/WifiSyncSettingsViewController.swift
- kDriveCore/Data/DownloadQueue/DownloadQueue.swift
- kDriveCore/Data/DownloadQueue/DownloadQueueable.swift
- kDriveCore/Data/UploadQueue/Queue/UploadQueue.swift
Root PR https://github.com/Infomaniak/ios-kDrive/pull/1440
> feat: Manage download of offline files with wifiOnly or cellular

- kDrive/AppRouter.swift
- kDrive/UI/Controller/Menu/Share/PublicShareSingleFileViewModel.swift
- kDrive/UI/Controller/Menu/Share/PublicShareViewModel.swift
- kDriveCore/Utils/AppNavigable.swift
- kDriveCore/Utils/Deeplinks/UniversalLinksHelper.swift
- kDriveCore/Utils/InExtensionRouter.swift
- kDriveTestShared/MCKRouter.swift
Support for opening 'public share' of a single file
> feat: Public share single file

- Tuist/Package.swift
To check the strings 2 tests: 
- Add a photo to the drive from the Apple photo gallery 
- Add a photo from kDrive
> fix: Add LocalizeKit to fix string

- kDriveCore/Data/Upload/UploadQueue/Operation/UploadOperation+Error.swift
> fix: Early exit on upload operation completed

- kDrive/UI/Controller/Files/ColorSelectionFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/File List/MultipleSelectionFileListViewModel.swift
- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
- kDrive/UI/Controller/Menu/SwitchUserViewController.swift
- kDrive/UI/Controller/Menu/Trash/TrashListViewModel.swift
- kDrive/Utils/FileActionsHelper.swift
- kDriveCore/Utils/Constants.swift
Some parallel API calls are not limited, here I make sure we do not do more than 4 requests in parallel.
> fix: Scaling issues

- kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
fix https://github.com/Infomaniak/ios-kDrive/issues/1534
> fix: Make sure a DB transaction is finished before we notify a change

- TestFlight/WhatToTest.en-GB.txt
- TestFlight/WhatToTest.fr-FR.txt
- Tuist/Package.resolved
This could be the last 5.7 beta
depends on https://github.com/Infomaniak/ios-kDrive/pull/1606
depends on https://github.com/Infomaniak/ios-kDrive/pull/1607
> chore: Release build 5.7.0-b29

- TestFlight/WhatToTest.en-GB.txt
- TestFlight/WhatToTest.fr-FR.txt
- Tuist/Package.resolved
- Tuist/ProjectDescriptionHelpers/Constants.swift
I'll open this for review as soon as I get QA's go.
> chore: Release build 5.8.1

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController+Actions.swift
- kDrive/UI/Controller/Files/Save File/LocationFolderViewController.swift
- kDrive/UI/Controller/Files/Save File/SelectFolderViewController.swift
- kDrive/Utils/FileActionsHelper.swift
Reverts Infomaniak/ios-kDrive#1625
> chore: Revert "fix: Prevent moving to a shared with me folder"

- kDrive/AppRouter+SharedWithMe.swift
- kDrive/AppRouter+Trash.swift
- kDrive/AppRouter.swift
- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
- kDriveCore/Utils/AppNavigable.swift
- kDriveCore/Utils/InExtensionRouter.swift
- kDriveTestShared/MCKRouter.swift
The action was broken since the UI changes of the iPad version
depends on https://github.com/Infomaniak/ios-kDrive/pull/1632
> fix: Duplicate bulk action

- kDrive/Resources/de.lproj/Localizable.strings
- kDrive/Resources/en.lproj/Localizable.strings
- kDrive/Resources/es.lproj/Localizable.strings
- kDrive/Resources/fr.lproj/Localizable.strings
- kDrive/Resources/it.lproj/Localizable.strings
This particular string was incorrectly formatted, this ended up using C strings instead of NSString. This would create encoding errors in the displayed strings.
Fixes: #1620
> fix: Correctly format strings

- kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController+Actions.swift
- kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/RightsSelectionViewController.swift
- kDrive/UI/Controller/Files/Rights and Share/ShareLinkSettingsViewController.swift
- kDrive/UI/Controller/Home/HomeViewController.swift
- kDrive/UI/Controller/Menu/MenuViewController.swift
- kDrive/UI/View/Files/FileDetail/ShareLink/RightsSelectionTableViewCell.swift
- kDrive/UI/View/Files/FileDetail/ShareLink/RightsSelectionTableViewCell.xib
- kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkSettingTableViewCell.swift
- kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkSettingTableViewCell.xib
- kDrive/UI/View/Home/InsufficientStorageCollectionViewCell.swift
- kDrive/UI/View/Home/InsufficientStorageCollectionViewCell.xib
- kDrive/Utils/FileActionsHelper.swift
- kDrive/Utils/KSuitePro/KSuiteGetProViewController.swift
- kDriveCore/Data/Models/Drive/Drive+Quota.swift
- kDriveCore/UI/UIConstants.swift
- kDriveCore/Utils/String+Extension.swift
depends on #1674
feature PR https://github.com/Infomaniak/ios-kDrive/pull/1644
✅ Shared settings
✅ Error banner
> feat: Support for kSuite pro part 2
